package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;

/**
 * AddressFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_ADDRESS")
public interface AddressFullEntity  {

    public static final String ADDRESS_ID = "addressId";
    public static final String USER = "userId";
    public static final String BUS_ENTITY = "busEntityId";
    public static final String NAME1 = "name1";
    public static final String NAME2 = "name2";
    public static final String ADDRESS1 = "address1";
    public static final String ADDRESS2 = "address2";
    public static final String ADDRESS3 = "address3";
    public static final String ADDRESS4 = "address4";
    public static final String CITY = "city";
    public static final String STATE_PROVINCE_CD = "stateProvinceCd";
    public static final String COUNTRY_CD = "countryCd";
    public static final String COUNTY_CD = "countyCd";
    public static final String POSTAL_CODE = "postalCode";
    public static final String ADDRESS_STATUS_CD = "addressStatusCd";
    public static final String ADDRESS_TYPE_CD = "addressTypeCd";
    public static final String PRIMARY_IND = "primaryInd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    public static final String USER_ID = "userId.userId";
    public static final String BUS_ENTITY_ID = "busEntityId.busEntityId";

    public void setAddressId(Long addressId);
    @SequenceGenerator(name="generator", sequenceName="CLW_ADDRESS_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="ADDRESS_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getAddressId();

    public void setUserId(UserFullEntity userId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="USER_ID", columnDefinition="number")
    public UserFullEntity getUserId();

    public void setBusEntityId(BusEntityFullEntity busEntityId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="BUS_ENTITY_ID", columnDefinition="number")
    public BusEntityFullEntity getBusEntityId();

    public void setName1(String name1);
    
    @Column(name="NAME1")
    public String getName1();

    public void setName2(String name2);
    
    @Column(name="NAME2")
    public String getName2();

    public void setAddress1(String address1);
    
    @Column(name="ADDRESS1")
    public String getAddress1();

    public void setAddress2(String address2);
    
    @Column(name="ADDRESS2")
    public String getAddress2();

    public void setAddress3(String address3);
    
    @Column(name="ADDRESS3")
    public String getAddress3();

    public void setAddress4(String address4);
    
    @Column(name="ADDRESS4")
    public String getAddress4();

    public void setCity(String city);
    
    @Column(name="CITY")
    public String getCity();

    public void setStateProvinceCd(String stateProvinceCd);
    
    @Column(name="STATE_PROVINCE_CD", length=30)
    public String getStateProvinceCd();

    public void setCountryCd(String countryCd);
    
    @Column(name="COUNTRY_CD")
    public String getCountryCd();

    public void setCountyCd(String countyCd);
    
    @Column(name="COUNTY_CD", length=50)
    public String getCountyCd();

    public void setPostalCode(String postalCode);
    
    @Column(name="POSTAL_CODE", length=15)
    public String getPostalCode();

    public void setAddressStatusCd(String addressStatusCd);
    
    @Column(name="ADDRESS_STATUS_CD", nullable=false, length=30)
    public String getAddressStatusCd();

    public void setAddressTypeCd(String addressTypeCd);
    
    @Column(name="ADDRESS_TYPE_CD", nullable=false, length=30)
    public String getAddressTypeCd();

    public void setPrimaryInd(Boolean primaryInd);
    @Type(type="com.espendwise.manta.support.hibernate.NumberBooleanType")
    @Column(name="PRIMARY_IND", columnDefinition="number", precision=1, scale=0)
    public Boolean getPrimaryInd();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

}

