package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AllStoreFullEntity generated by hbm2java
*/
@Entity
@Table(name="ESW_ALL_STORE")
public interface AllStoreFullEntity  {

    public static final String ALL_STORE_ID = "allStoreId";
    public static final String STORE_ID = "storeId";
    public static final String STORE_NAME = "storeName";
    public static final String DOMAIN = "domain";
    public static final String DATASOURCE = "datasource";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String USER_STORES = "userStores";


    public void setAllStoreId(Long allStoreId);
    @SequenceGenerator(name="generator", sequenceName="ESW_ALL_STORE_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="ALL_STORE_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getAllStoreId();

    public void setStoreId(Long storeId);
    
    @Column(name="STORE_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getStoreId();

    public void setStoreName(String storeName);
    
    @Column(name="STORE_NAME")
    public String getStoreName();

    public void setDomain(String domain);
    
    @Column(name="DOMAIN")
    public String getDomain();

    public void setDatasource(String datasource);
    
    @Column(name="DATASOURCE")
    public String getDatasource();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setUserStores(Set<UserStoreFullEntity> userStores);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="allStoreId")
    public Set<UserStoreFullEntity> getUserStores();

}

