package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AllUserFullEntity generated by hbm2java
*/
@Entity
@Table(name="ESW_ALL_USER")
public interface AllUserFullEntity  {

    public static final String ALL_USER_ID = "allUserId";
    public static final String USER_ID = "userId";
    public static final String USER_NAME = "userName";
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String PASSWORD = "password";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String USER_STATUS_CD = "userStatusCd";
    public static final String USER_TYPE_CD = "userTypeCd";
    public static final String DEFAULT_STORE_ID = "defaultStoreId";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String USER_STORES = "userStores";


    public void setAllUserId(Long allUserId);
    @SequenceGenerator(name="generator", sequenceName="ESW_ALL_USER_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="ALL_USER_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getAllUserId();

    public void setUserId(Long userId);
    
    @Column(name="USER_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getUserId();

    public void setUserName(String userName);
    
    @Column(name="USER_NAME", nullable=false)
    public String getUserName();

    public void setFirstName(String firstName);
    
    @Column(name="FIRST_NAME")
    public String getFirstName();

    public void setLastName(String lastName);
    
    @Column(name="LAST_NAME")
    public String getLastName();

    public void setPassword(String password);
    
    @Column(name="PASSWORD", length=35)
    public String getPassword();

    public void setEffDate(Date effDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFF_DATE", length=7)
    public Date getEffDate();

    public void setExpDate(Date expDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXP_DATE", length=7)
    public Date getExpDate();

    public void setUserStatusCd(String userStatusCd);
    
    @Column(name="USER_STATUS_CD", nullable=false, length=30)
    public String getUserStatusCd();

    public void setUserTypeCd(String userTypeCd);
    
    @Column(name="USER_TYPE_CD", nullable=false, length=30)
    public String getUserTypeCd();

    public void setDefaultStoreId(Long defaultStoreId);
    
    @Column(name="DEFAULT_STORE_ID", columnDefinition="number", precision=38, scale=0)
    public Long getDefaultStoreId();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setUserStores(Set<UserStoreFullEntity> userStores);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="allUserId")
    public Set<UserStoreFullEntity> getUserStores();

}

