package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BudgetDetailFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_BUDGET_DETAIL")
public interface BudgetDetailFullEntity  {

    public static final String BUDGET_DETAIL_ID = "budgetDetailId";
    public static final String BUDGET = "budgetId";
    public static final String PERIOD = "period";
    public static final String AMOUNT = "amount";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    public static final String BUDGET_ID = "budgetId.budgetId";

    public void setBudgetDetailId(Long budgetDetailId);
    @SequenceGenerator(name="generator", sequenceName="CLW_BUDGET_DETAIL_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="BUDGET_DETAIL_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBudgetDetailId();

    public void setBudgetId(BudgetFullEntity budgetId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="BUDGET_ID", nullable=false, columnDefinition="number")
    public BudgetFullEntity getBudgetId();

    public void setPeriod(int period);
    
    @Column(name="PERIOD", nullable=false, columnDefinition="number", precision=10, scale=0)
    public int getPeriod();

    public void setAmount(BigDecimal amount);
    
    @Column(name="AMOUNT", columnDefinition="number", precision=20, scale=8)
    public BigDecimal getAmount();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

}

