package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BudgetFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_BUDGET")
public interface BudgetFullEntity  {

    public static final String BUDGET_ID = "budgetId";
    public static final String COST_CENTER = "costCenterId";
    public static final String BUS_ENTITY = "busEntityId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String BUDGET_STATUS_CD = "budgetStatusCd";
    public static final String BUDGET_TYPE_CD = "budgetTypeCd";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String BUDGET_THRESHOLD = "budgetThreshold";
    public static final String BUDGET_YEAR = "budgetYear";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String AMOUNT1 = "amount1";
    public static final String AMOUNT2 = "amount2";
    public static final String AMOUNT3 = "amount3";
    public static final String AMOUNT4 = "amount4";
    public static final String AMOUNT5 = "amount5";
    public static final String AMOUNT6 = "amount6";
    public static final String AMOUNT7 = "amount7";
    public static final String AMOUNT8 = "amount8";
    public static final String AMOUNT9 = "amount9";
    public static final String AMOUNT10 = "amount10";
    public static final String AMOUNT11 = "amount11";
    public static final String AMOUNT12 = "amount12";
    public static final String AMOUNT13 = "amount13";
    public static final String BUDGET_DETAILS = "budgetDetails";

    public static final String COST_CENTER_ID = "costCenterId.costCenterId";
    public static final String BUS_ENTITY_ID = "busEntityId.busEntityId";

    public void setBudgetId(Long budgetId);
    @SequenceGenerator(name="generator", sequenceName="CLW_BUDGET_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="BUDGET_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBudgetId();

    public void setCostCenterId(CostCenterFullEntity costCenterId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="COST_CENTER_ID", nullable=false, columnDefinition="number")
    public CostCenterFullEntity getCostCenterId();

    public void setBusEntityId(BusEntityFullEntity busEntityId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="BUS_ENTITY_ID", nullable=false, columnDefinition="number")
    public BusEntityFullEntity getBusEntityId();

    public void setShortDesc(String shortDesc);
    
    @Column(name="SHORT_DESC")
    public String getShortDesc();

    public void setBudgetStatusCd(String budgetStatusCd);
    
    @Column(name="BUDGET_STATUS_CD", nullable=false, length=30)
    public String getBudgetStatusCd();

    public void setBudgetTypeCd(String budgetTypeCd);
    
    @Column(name="BUDGET_TYPE_CD", nullable=false, length=30)
    public String getBudgetTypeCd();

    public void setEffDate(Date effDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFF_DATE", length=7)
    public Date getEffDate();

    public void setExpDate(Date expDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXP_DATE", length=7)
    public Date getExpDate();

    public void setBudgetThreshold(String budgetThreshold);
    
    @Column(name="BUDGET_THRESHOLD", length=10)
    public String getBudgetThreshold();

    public void setBudgetYear(int budgetYear);
    
    @Column(name="BUDGET_YEAR", nullable=false, columnDefinition="number", precision=5, scale=0)
    public int getBudgetYear();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setAmount1(BigDecimal amount1);
    
    @Column(name="AMOUNT1", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount1();

    public void setAmount2(BigDecimal amount2);
    
    @Column(name="AMOUNT2", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount2();

    public void setAmount3(BigDecimal amount3);
    
    @Column(name="AMOUNT3", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount3();

    public void setAmount4(BigDecimal amount4);
    
    @Column(name="AMOUNT4", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount4();

    public void setAmount5(BigDecimal amount5);
    
    @Column(name="AMOUNT5", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount5();

    public void setAmount6(BigDecimal amount6);
    
    @Column(name="AMOUNT6", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount6();

    public void setAmount7(BigDecimal amount7);
    
    @Column(name="AMOUNT7", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount7();

    public void setAmount8(BigDecimal amount8);
    
    @Column(name="AMOUNT8", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount8();

    public void setAmount9(BigDecimal amount9);
    
    @Column(name="AMOUNT9", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount9();

    public void setAmount10(BigDecimal amount10);
    
    @Column(name="AMOUNT10", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount10();

    public void setAmount11(BigDecimal amount11);
    
    @Column(name="AMOUNT11", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount11();

    public void setAmount12(BigDecimal amount12);
    
    @Column(name="AMOUNT12", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount12();

    public void setAmount13(BigDecimal amount13);
    
    @Column(name="AMOUNT13", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount13();

    public void setBudgetDetails(Set<BudgetDetailFullEntity> budgetDetails);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="budgetId")
    public Set<BudgetDetailFullEntity> getBudgetDetails();

}

