package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatalogAssocFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_CATALOG_ASSOC")
public interface CatalogAssocFullEntity  {

    public static final String CATALOG_ASSOC_ID = "catalogAssocId";
    public static final String BUS_ENTITY = "busEntityId";
    public static final String CATALOG = "catalogId";
    public static final String CATALOG_ASSOC_CD = "catalogAssocCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String NEW_CATALOG_ID = "newCatalogId";

    public static final String BUS_ENTITY_ID = "busEntityId.busEntityId";
    public static final String CATALOG_ID = "catalogId.catalogId";

    public void setCatalogAssocId(Long catalogAssocId);
    @SequenceGenerator(name="generator", sequenceName="CLW_CATALOG_ASSOC_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="CATALOG_ASSOC_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getCatalogAssocId();

    public void setBusEntityId(BusEntityFullEntity busEntityId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="BUS_ENTITY_ID", nullable=false, columnDefinition="number")
    public BusEntityFullEntity getBusEntityId();

    public void setCatalogId(CatalogFullEntity catalogId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="CATALOG_ID", nullable=false, columnDefinition="number")
    public CatalogFullEntity getCatalogId();

    public void setCatalogAssocCd(String catalogAssocCd);
    
    @Column(name="CATALOG_ASSOC_CD", nullable=false, length=30)
    public String getCatalogAssocCd();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setNewCatalogId(Long newCatalogId);
    
    @Column(name="NEW_CATALOG_ID", columnDefinition="number", precision=38, scale=0)
    public Long getNewCatalogId();

}

