package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * ContentFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_CONTENT")
public interface ContentFullEntity  {

    public static final String CONTENT_ID = "contentId";
    public static final String VERSION = "version";
    public static final String ITEM = "itemId";
    public static final String BUS_ENTITY = "busEntityId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String LONG_DESC = "longDesc";
    public static final String CONTENT_TYPE_CD = "contentTypeCd";
    public static final String CONTENT_STATUS_CD = "contentStatusCd";
    public static final String SOURCE_CD = "sourceCd";
    public static final String LOCALE_CD = "localeCd";
    public static final String LANGUAGE_CD = "languageCd";
    public static final String PATH = "path";
    public static final String CONTENT_USAGE_CD = "contentUsageCd";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String BINARY_DATA = "binaryData";

    public static final String ITEM_ID = "itemId.itemId";
    public static final String BUS_ENTITY_ID = "busEntityId.busEntityId";

    public void setContentId(Long contentId);
    @SequenceGenerator(name="generator", sequenceName="CLW_CONTENT_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="CONTENT_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getContentId();

    public void setVersion(Long version);

    @Column(name="VERSION", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getVersion();

    public void setItemId(ItemFullEntity itemId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="ITEM_ID", columnDefinition="number")
    public ItemFullEntity getItemId();

    public void setBusEntityId(BusEntityFullEntity busEntityId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="BUS_ENTITY_ID", columnDefinition="number")
    public BusEntityFullEntity getBusEntityId();

    public void setShortDesc(String shortDesc);
    
    @Column(name="SHORT_DESC", nullable=false, length=30)
    public String getShortDesc();

    public void setLongDesc(String longDesc);
    
    @Column(name="LONG_DESC")
    public String getLongDesc();

    public void setContentTypeCd(String contentTypeCd);
    
    @Column(name="CONTENT_TYPE_CD", nullable=false, length=30)
    public String getContentTypeCd();

    public void setContentStatusCd(String contentStatusCd);
    
    @Column(name="CONTENT_STATUS_CD", nullable=false, length=30)
    public String getContentStatusCd();

    public void setSourceCd(String sourceCd);
    
    @Column(name="SOURCE_CD", nullable=false, length=30)
    public String getSourceCd();

    public void setLocaleCd(String localeCd);
    
    @Column(name="LOCALE_CD", nullable=false, length=30)
    public String getLocaleCd();

    public void setLanguageCd(String languageCd);
    
    @Column(name="LANGUAGE_CD", nullable=false, length=30)
    public String getLanguageCd();

    public void setPath(String path);
    
    @Column(name="PATH")
    public String getPath();

    public void setContentUsageCd(String contentUsageCd);
    
    @Column(name="CONTENT_USAGE_CD", nullable=false, length=30)
    public String getContentUsageCd();

    public void setEffDate(Date effDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFF_DATE", length=7)
    public Date getEffDate();

    public void setExpDate(Date expDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXP_DATE", length=7)
    public Date getExpDate();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY", length=1000)
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY", length=1000)
    public String getModBy();

    public void setBinaryData(byte[] binaryData);
    
    @Column(name="BINARY_DATA", columnDefinition="blob")
    public byte[] getBinaryData();

}

