package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FiscalCalenderFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_FISCAL_CALENDER")
public interface FiscalCalenderFullEntity  {

    public static final String FISCAL_CALENDER_ID = "fiscalCalenderId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String PERIOD_CD = "periodCd";
    public static final String MMDD1 = "mmdd1";
    public static final String MMDD2 = "mmdd2";
    public static final String MMDD3 = "mmdd3";
    public static final String MMDD4 = "mmdd4";
    public static final String MMDD5 = "mmdd5";
    public static final String MMDD6 = "mmdd6";
    public static final String MMDD7 = "mmdd7";
    public static final String MMDD8 = "mmdd8";
    public static final String MMDD9 = "mmdd9";
    public static final String MMDD10 = "mmdd10";
    public static final String MMDD11 = "mmdd11";
    public static final String MMDD12 = "mmdd12";
    public static final String MMDD13 = "mmdd13";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String FISCAL_YEAR = "fiscalYear";
    public static final String FISCAL_CALENDER_DETAILS = "fiscalCalenderDetails";


    public void setFiscalCalenderId(Long fiscalCalenderId);
    @SequenceGenerator(name="generator", sequenceName="CLW_FISCAL_CALENDER_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="FISCAL_CALENDER_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getFiscalCalenderId();

    public void setBusEntityId(Long busEntityId);
    
    @Column(name="BUS_ENTITY_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBusEntityId();

    public void setShortDesc(String shortDesc);
    
    @Column(name="SHORT_DESC", nullable=false, length=30)
    public String getShortDesc();

    public void setPeriodCd(String periodCd);
    
    @Column(name="PERIOD_CD", nullable=false, length=30)
    public String getPeriodCd();

    public void setMmdd1(String mmdd1);
    
    @Column(name="MMDD1", length=5)
    public String getMmdd1();

    public void setMmdd2(String mmdd2);
    
    @Column(name="MMDD2", length=5)
    public String getMmdd2();

    public void setMmdd3(String mmdd3);
    
    @Column(name="MMDD3", length=5)
    public String getMmdd3();

    public void setMmdd4(String mmdd4);
    
    @Column(name="MMDD4", length=5)
    public String getMmdd4();

    public void setMmdd5(String mmdd5);
    
    @Column(name="MMDD5", length=5)
    public String getMmdd5();

    public void setMmdd6(String mmdd6);
    
    @Column(name="MMDD6", length=5)
    public String getMmdd6();

    public void setMmdd7(String mmdd7);
    
    @Column(name="MMDD7", length=5)
    public String getMmdd7();

    public void setMmdd8(String mmdd8);
    
    @Column(name="MMDD8", length=5)
    public String getMmdd8();

    public void setMmdd9(String mmdd9);
    
    @Column(name="MMDD9", length=5)
    public String getMmdd9();

    public void setMmdd10(String mmdd10);
    
    @Column(name="MMDD10", length=5)
    public String getMmdd10();

    public void setMmdd11(String mmdd11);
    
    @Column(name="MMDD11", length=5)
    public String getMmdd11();

    public void setMmdd12(String mmdd12);
    
    @Column(name="MMDD12", length=5)
    public String getMmdd12();

    public void setMmdd13(String mmdd13);
    
    @Column(name="MMDD13", length=5)
    public String getMmdd13();

    public void setEffDate(Date effDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFF_DATE", nullable=false, length=7)
    public Date getEffDate();

    public void setExpDate(Date expDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXP_DATE", length=7)
    public Date getExpDate();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setFiscalYear(Integer fiscalYear);
    
    @Column(name="FISCAL_YEAR", columnDefinition="number", precision=5, scale=0)
    public Integer getFiscalYear();

    public void setFiscalCalenderDetails(Set<FiscalCalenderDetailFullEntity> fiscalCalenderDetails);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="fiscalCalenderId")
    public Set<FiscalCalenderDetailFullEntity> getFiscalCalenderDetails();

}

