package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderAssocFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_ORDER_ASSOC")
public interface OrderAssocFullEntity  {

    public static final String ORDER_ASSOC_ID = "orderAssocId";
    public static final String ORDER2 = "order2Id";
    public static final String ORDER1 = "order1Id";
    public static final String ORDER_ASSOC_CD = "orderAssocCd";
    public static final String ORDER_ASSOC_STATUS_CD = "orderAssocStatusCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String WORK_ORDER_ITEM_ID = "workOrderItemId";
    public static final String SERVICE_TICKET_ID = "serviceTicketId";

    public static final String ORDER2_ID = "order2Id.orderId";
    public static final String ORDER1_ID = "order1Id.orderId";

    public void setOrderAssocId(Long orderAssocId);
    @SequenceGenerator(name="generator", sequenceName="CLW_ORDER_ASSOC_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="ORDER_ASSOC_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getOrderAssocId();

    public void setOrder2Id(OrderFullEntity order2Id);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="ORDER2_ID", nullable=false, columnDefinition="number")
    public OrderFullEntity getOrder2Id();

    public void setOrder1Id(OrderFullEntity order1Id);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="ORDER1_ID", columnDefinition="number")
    public OrderFullEntity getOrder1Id();

    public void setOrderAssocCd(String orderAssocCd);
    
    @Column(name="ORDER_ASSOC_CD", length=30)
    public String getOrderAssocCd();

    public void setOrderAssocStatusCd(String orderAssocStatusCd);
    
    @Column(name="ORDER_ASSOC_STATUS_CD", length=30)
    public String getOrderAssocStatusCd();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setWorkOrderItemId(Long workOrderItemId);
    
    @Column(name="WORK_ORDER_ITEM_ID", columnDefinition="number", precision=38, scale=0)
    public Long getWorkOrderItemId();

    public void setServiceTicketId(Long serviceTicketId);
    
    @Column(name="SERVICE_TICKET_ID", columnDefinition="number", precision=38, scale=0)
    public Long getServiceTicketId();

}

