package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PropertyFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_PROPERTY")
public interface PropertyFullEntity  {

    public static final String PROPERTY_ID = "propertyId";
    public static final String USER = "userId";
    public static final String BUS_ENTITY = "busEntityId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String VALUE = "value";
    public static final String PROPERTY_STATUS_CD = "propertyStatusCd";
    public static final String PROPERTY_TYPE_CD = "propertyTypeCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String LOCALE_CD = "localeCd";
    public static final String ORIGINAL_USER_ID = "originalUserId";

    public static final String USER_ID = "userId.userId";
    public static final String BUS_ENTITY_ID = "busEntityId.busEntityId";

    public void setPropertyId(Long propertyId);
    @SequenceGenerator(name="generator", sequenceName="CLW_PROPERTY_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="PROPERTY_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getPropertyId();

    public void setUserId(UserFullEntity userId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="USER_ID", columnDefinition="number")
    public UserFullEntity getUserId();

    public void setBusEntityId(BusEntityFullEntity busEntityId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="BUS_ENTITY_ID", columnDefinition="number")
    public BusEntityFullEntity getBusEntityId();

    public void setShortDesc(String shortDesc);
    
    @Column(name="SHORT_DESC")
    public String getShortDesc();

    public void setValue(String value);
    
    @Column(name="CLW_VALUE", length=4000)
    public String getValue();

    public void setPropertyStatusCd(String propertyStatusCd);
    
    @Column(name="PROPERTY_STATUS_CD", nullable=false, length=30)
    public String getPropertyStatusCd();

    public void setPropertyTypeCd(String propertyTypeCd);
    
    @Column(name="PROPERTY_TYPE_CD", nullable=false, length=30)
    public String getPropertyTypeCd();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setLocaleCd(String localeCd);
    
    @Column(name="LOCALE_CD", length=5)
    public String getLocaleCd();

    public void setOriginalUserId(Long originalUserId);
    
    @Column(name="ORIGINAL_USER_ID", columnDefinition="number", precision=38, scale=0)
    public Long getOriginalUserId();

}

