package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RefCdFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_REF_CD")
public interface RefCdFullEntity  {

    public static final String REF_CD_ID = "refCdId";
    public static final String REF_CD = "refCd";
    public static final String SHORT_DESC = "shortDesc";
    public static final String VALUE = "value";
    public static final String REF_CD_TYPE = "refCdType";
    public static final String REF_STATUS_CD = "refStatusCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";


    public void setRefCdId(Long refCdId);
    @SequenceGenerator(name="generator", sequenceName="CLW_REF_CD_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="REF_CD_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getRefCdId();

    public void setRefCd(String refCd);
    
    @Column(name="REF_CD", nullable=false, length=30)
    public String getRefCd();

    public void setShortDesc(String shortDesc);
    
    @Column(name="SHORT_DESC", nullable=false)
    public String getShortDesc();

    public void setValue(String value);
    
    @Column(name="CLW_VALUE", nullable=false)
    public String getValue();

    public void setRefCdType(String refCdType);
    
    @Column(name="REF_CD_TYPE", nullable=false, length=30)
    public String getRefCdType();

    public void setRefStatusCd(String refStatusCd);
    
    @Column(name="REF_STATUS_CD", nullable=false, length=30)
    public String getRefStatusCd();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

}

