package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StoreMessageAssocFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_STORE_MESSAGE_ASSOC")
public interface StoreMessageAssocFullEntity  {

    public static final String STORE_MESSAGE_ASSOC_ID = "storeMessageAssocId";
    public static final String BUS_ENTITY = "busEntityId";
    public static final String STORE_MESSAGE = "storeMessageId";
    public static final String STORE_MESSAGE_ASSOC_CD = "storeMessageAssocCd";
    public static final String ADD_BY = "addBy";
    public static final String ADD_DATE = "addDate";
    public static final String MOD_BY = "modBy";
    public static final String MOD_DATE = "modDate";

    public static final String BUS_ENTITY_ID = "busEntityId.busEntityId";
    public static final String STORE_MESSAGE_ID = "storeMessageId.storeMessageId";

    public void setStoreMessageAssocId(Long storeMessageAssocId);
    @SequenceGenerator(name="generator", sequenceName="CLW_STORE_MESSAGE_ASSOC_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="STORE_MESSAGE_ASSOC_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getStoreMessageAssocId();

    public void setBusEntityId(BusEntityFullEntity busEntityId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="BUS_ENTITY_ID", nullable=false, columnDefinition="number")
    public BusEntityFullEntity getBusEntityId();

    public void setStoreMessageId(StoreMessageFullEntity storeMessageId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="STORE_MESSAGE_ID", nullable=false, columnDefinition="number")
    public StoreMessageFullEntity getStoreMessageId();

    public void setStoreMessageAssocCd(String storeMessageAssocCd);
    
    @Column(name="STORE_MESSAGE_ASSOC_CD", length=30)
    public String getStoreMessageAssocCd();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

}

