package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TemplateFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_TEMPLATE")
public interface TemplateFullEntity  {

    public static final String TEMPLATE_ID = "templateId";
    public static final String BUS_ENTITY = "busEntityId";
    public static final String NAME = "name";
    public static final String TYPE = "type";
    public static final String CONTENT = "content";
    public static final String ADD_BY = "addBy";
    public static final String ADD_DATE = "addDate";
    public static final String MOD_BY = "modBy";
    public static final String MOD_DATE = "modDate";
    public static final String TEMPLATE_PROPERTIES = "templateProperties";

    public static final String BUS_ENTITY_ID = "busEntityId.busEntityId";

    public void setTemplateId(Long templateId);
    @SequenceGenerator(name="generator", sequenceName="CLW_TEMPLATE_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="TEMPLATE_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getTemplateId();

    public void setBusEntityId(BusEntityFullEntity busEntityId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="BUS_ENTITY_ID", columnDefinition="number")
    public BusEntityFullEntity getBusEntityId();

    public void setName(String name);
    
    @Column(name="NAME", nullable=false, length=50)
    public String getName();

    public void setType(String type);
    
    @Column(name="TYPE", nullable=false, length=30)
    public String getType();

    public void setContent(String content);
    
    @Column(name="CONTENT", nullable=false, columnDefinition="clob")
    public String getContent();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setTemplateProperties(Set<TemplatePropertyFullEntity> templateProperties);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="templateId")
    public Set<TemplatePropertyFullEntity> getTemplateProperties();

}

