package com.espendwise.manta.model.fullentity;

// Generated by Hibernate Tools

import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserAssocFullEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_USER_ASSOC")
public interface UserAssocFullEntity  {

    public static final String USER_ASSOC_ID = "userAssocId";
    public static final String USER = "userId";
    public static final String BUS_ENTITY = "busEntityId";
    public static final String USER_ASSOC_CD = "userAssocCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String LAST_USER_VISIT_DATE_TIME = "lastUserVisitDateTime";

    public static final String USER_ID = "userId.userId";
    public static final String BUS_ENTITY_ID = "busEntityId.busEntityId";

    public void setUserAssocId(Long userAssocId);
    @SequenceGenerator(name="generator", sequenceName="CLW_USER_ASSOC_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="USER_ASSOC_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getUserAssocId();

    public void setUserId(UserFullEntity userId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="USER_ID", columnDefinition="number")
    public UserFullEntity getUserId();

    public void setBusEntityId(BusEntityFullEntity busEntityId);
    @ManyToOne(fetch=FetchType.LAZY)    @JoinColumn(name="BUS_ENTITY_ID", columnDefinition="number")
    public BusEntityFullEntity getBusEntityId();

    public void setUserAssocCd(String userAssocCd);
    
    @Column(name="USER_ASSOC_CD", nullable=false, length=30)
    public String getUserAssocCd();

    public void setAddDate(Date addDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate();

    public void setAddBy(String addBy);
    
    @Column(name="ADD_BY")
    public String getAddBy();

    public void setModDate(Date modDate);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate();

    public void setModBy(String modBy);
    
    @Column(name="MOD_BY")
    public String getModBy();

    public void setLastUserVisitDateTime(Date lastUserVisitDateTime);
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_USER_VISIT_DATE_TIME", length=7)
    public Date getLastUserVisitDateTime();

}

