package com.espendwise.manta.model.entity;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
/**
 * BusEntityMessageAssocEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_STORE_MESSAGE_ASSOC")
public class BusEntityMessageAssocEntity extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String STORE_MESSAGE_ASSOC_ID = "storeMessageAssocId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String STORE_MESSAGE_ID = "storeMessageId";
    public static final String STORE_MESSAGE_ASSOC_CD = "storeMessageAssocCd";
    public static final String MESSAGES = "messages";

    private Long storeMessageAssocId;
    private Long busEntityId;
    private Long storeMessageId;
    private String storeMessageAssocCd;
    private StoreMessageListEntity messages;

    public BusEntityMessageAssocEntity() {
    }
	
    public BusEntityMessageAssocEntity(Long storeMessageAssocId) {
        this.setStoreMessageAssocId(storeMessageAssocId);
    }

    public BusEntityMessageAssocEntity(Long storeMessageAssocId, Long busEntityId, Long storeMessageId, String storeMessageAssocCd, StoreMessageListEntity messages) {
        this.setStoreMessageAssocId(storeMessageAssocId);
        this.setBusEntityId(busEntityId);
        this.setStoreMessageId(storeMessageId);
        this.setStoreMessageAssocCd(storeMessageAssocCd);
        this.setMessages(messages);
    }

    @Id      
    @Column(name="STORE_MESSAGE_ASSOC_ID", nullable=false)
    public Long getStoreMessageAssocId() {
        return this.storeMessageAssocId;
    }

    public void setStoreMessageAssocId(Long storeMessageAssocId) {
        this.storeMessageAssocId = storeMessageAssocId;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_ID", insertable=false, updatable=false)
    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    
    @Column(name="STORE_MESSAGE_ID", insertable=false, updatable=false)
    public Long getStoreMessageId() {
        return this.storeMessageId;
    }

    public void setStoreMessageId(Long storeMessageId) {
        this.storeMessageId = storeMessageId;
        setDirty(true);
    }

    
    @Column(name="STORE_MESSAGE_ASSOC_CD")
    public String getStoreMessageAssocCd() {
        return this.storeMessageAssocCd;
    }

    public void setStoreMessageAssocCd(String storeMessageAssocCd) {
        this.storeMessageAssocCd = storeMessageAssocCd;
        setDirty(true);
    }

    @ManyToOne(fetch=FetchType.EAGER)    @JoinColumn(name="STORE_MESSAGE_ID", insertable=false, updatable=false)
    public StoreMessageListEntity getMessages() {
        return this.messages;
    }

    public void setMessages(StoreMessageListEntity messages) {
        this.messages = messages;
        setDirty(true);
    }




}


