package com.espendwise.manta.model.entity;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.AddressData;
import com.espendwise.manta.model.data.EmailData;
import com.espendwise.manta.model.data.PhoneData;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
/**
 * EntityContactEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_BUS_ENTITY")
public class EntityContactEntity extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String ADDRESS = "address";
    public static final String PHONE = "phone";
    public static final String EMAIL = "email";

    private Long busEntityId;
    private Set<AddressData> address = new HashSet<AddressData>(0);
    private Set<PhoneData> phone = new HashSet<PhoneData>(0);
    private Set<EmailData> email = new HashSet<EmailData>(0);

    public EntityContactEntity() {
    }
	
    public EntityContactEntity(Long busEntityId) {
        this.setBusEntityId(busEntityId);
    }

    public EntityContactEntity(Long busEntityId, Set<AddressData> address, Set<PhoneData> phone, Set<EmailData> email) {
        this.setBusEntityId(busEntityId);
        this.setAddress(address);
        this.setPhone(phone);
        this.setEmail(email);
    }

    @Id      
    @Column(name="BUS_ENTITY_ID", nullable=false)
    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    @OneToMany(fetch=FetchType.EAGER)
    @JoinColumn(name="BUS_ENTITY_ID", updatable=false, columnDefinition="number")
    public Set<AddressData> getAddress() {
        return this.address;
    }

    public void setAddress(Set<AddressData> address) {
        this.address = address;
        setDirty(true);
    }

    @OneToMany(fetch=FetchType.EAGER)
    @JoinColumn(name="BUS_ENTITY_ID", updatable=false, columnDefinition="number")
    public Set<PhoneData> getPhone() {
        return this.phone;
    }

    public void setPhone(Set<PhoneData> phone) {
        this.phone = phone;
        setDirty(true);
    }

    @OneToMany(fetch=FetchType.EAGER)
    @JoinColumn(name="BUS_ENTITY_ID", updatable=false, columnDefinition="number")
    public Set<EmailData> getEmail() {
        return this.email;
    }

    public void setEmail(Set<EmailData> email) {
        this.email = email;
        setDirty(true);
    }




}


