package com.espendwise.manta.model.entity;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * StoreMessageListEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_STORE_MESSAGE")
public class StoreMessageListEntity extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String STORE_MESSAGE_ID = "storeMessageId";
    public static final String MESSAGE_TITLE = "messageTitle";
    public static final String SHORT_DESC = "shortDesc";
    public static final String MESSAGE_TYPE = "messageType";
    public static final String POSTED_DATE = "postedDate";
    public static final String END_DATE = "endDate";
    public static final String FORCED_READ = "forcedRead";
    public static final String HOW_MANY_TIMES = "howManyTimes";
    public static final String PUBLISHED = "published";
    public static final String LANGUAGE_CD = "languageCd";
    public static final String COUNTRY = "country";
    public static final String MOD_BY = "modBy";
    public static final String MESSAGE_AUTHOR = "messageAuthor";
    public static final String MESSAGE_ABSTRACT = "messageAbstract";
    public static final String MESSAGE_BODY = "messageBody";
    public static final String STORE_MESSAGE_STATUS_CD = "storeMessageStatusCd";

    private Long storeMessageId;
    private String messageTitle;
    private String shortDesc;
    private String messageType;
    private Date postedDate;
    private Date endDate;
    private String forcedRead;
    private Long howManyTimes;
    private String published;
    private String languageCd;
    private String country;
    private String modBy;
    private String messageAuthor;
    private String messageAbstract;
    private String messageBody;
    private String storeMessageStatusCd;

    public StoreMessageListEntity() {
    }
	
    public StoreMessageListEntity(Long storeMessageId, String messageTitle, String languageCd, String messageAuthor, String messageAbstract, String storeMessageStatusCd) {
        this.setStoreMessageId(storeMessageId);
        this.setMessageTitle(messageTitle);
        this.setLanguageCd(languageCd);
        this.setMessageAuthor(messageAuthor);
        this.setMessageAbstract(messageAbstract);
        this.setStoreMessageStatusCd(storeMessageStatusCd);
    }

    public StoreMessageListEntity(Long storeMessageId, String messageTitle, String shortDesc, String messageType, Date postedDate, Date endDate, String forcedRead, Long howManyTimes, String published, String languageCd, String country, String modBy, String messageAuthor, String messageAbstract, String messageBody, String storeMessageStatusCd) {
        this.setStoreMessageId(storeMessageId);
        this.setMessageTitle(messageTitle);
        this.setShortDesc(shortDesc);
        this.setMessageType(messageType);
        this.setPostedDate(postedDate);
        this.setEndDate(endDate);
        this.setForcedRead(forcedRead);
        this.setHowManyTimes(howManyTimes);
        this.setPublished(published);
        this.setLanguageCd(languageCd);
        this.setCountry(country);
        this.setModBy(modBy);
        this.setMessageAuthor(messageAuthor);
        this.setMessageAbstract(messageAbstract);
        this.setMessageBody(messageBody);
        this.setStoreMessageStatusCd(storeMessageStatusCd);
    }

    @Id      
    @Column(name="STORE_MESSAGE_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getStoreMessageId() {
        return this.storeMessageId;
    }

    public void setStoreMessageId(Long storeMessageId) {
        this.storeMessageId = storeMessageId;
        setDirty(true);
    }

    
    @Column(name="MESSAGE_TITLE", nullable=false)
    public String getMessageTitle() {
        return this.messageTitle;
    }

    public void setMessageTitle(String messageTitle) {
        this.messageTitle = messageTitle;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC")
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="MESSAGE_TYPE")
    public String getMessageType() {
        return this.messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="POSTED_DATE")
    public Date getPostedDate() {
        return this.postedDate;
    }

    public void setPostedDate(Date postedDate) {
        this.postedDate = postedDate;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_DATE")
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
        setDirty(true);
    }

    
    @Column(name="FORCED_READ")
    public String getForcedRead() {
        return this.forcedRead;
    }

    public void setForcedRead(String forcedRead) {
        this.forcedRead = forcedRead;
        setDirty(true);
    }

    
    @Column(name="HOW_MANY_TIMES", columnDefinition="number")
    public Long getHowManyTimes() {
        return this.howManyTimes;
    }

    public void setHowManyTimes(Long howManyTimes) {
        this.howManyTimes = howManyTimes;
        setDirty(true);
    }

    
    @Column(name="PUBLISHED")
    public String getPublished() {
        return this.published;
    }

    public void setPublished(String published) {
        this.published = published;
        setDirty(true);
    }

    
    @Column(name="LANGUAGE_CD", nullable=false)
    public String getLanguageCd() {
        return this.languageCd;
    }

    public void setLanguageCd(String languageCd) {
        this.languageCd = languageCd;
        setDirty(true);
    }

    
    @Column(name="COUNTRY")
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="MESSAGE_AUTHOR", nullable=false)
    public String getMessageAuthor() {
        return this.messageAuthor;
    }

    public void setMessageAuthor(String messageAuthor) {
        this.messageAuthor = messageAuthor;
        setDirty(true);
    }

    
    @Column(name="MESSAGE_ABSTRACT", nullable=false)
    public String getMessageAbstract() {
        return this.messageAbstract;
    }

    public void setMessageAbstract(String messageAbstract) {
        this.messageAbstract = messageAbstract;
        setDirty(true);
    }

    
    @Column(name="MESSAGE_BODY")
    public String getMessageBody() {
        return this.messageBody;
    }

    public void setMessageBody(String messageBody) {
        this.messageBody = messageBody;
        setDirty(true);
    }

    
    @Column(name="STORE_MESSAGE_STATUS_CD", nullable=false)
    public String getStoreMessageStatusCd() {
        return this.storeMessageStatusCd;
    }

    public void setStoreMessageStatusCd(String storeMessageStatusCd) {
        this.storeMessageStatusCd = storeMessageStatusCd;
        setDirty(true);
    }




}


