package com.espendwise.manta.model.entity;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.AddressData;
import java.util.ArrayList;
import java.util.Collection;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
/**
 * StoreListEntity generated by hbm2java
*/
@Entity
@Table(name="CLW_BUS_ENTITY")
public class StoreListEntity extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String STORE_ID = "storeId";
    public static final String STORE_NAME = "storeName";
    public static final String STATUS = "status";
    public static final String BUS_ENTITY_TYPE_CD = "busEntityTypeCd";
    public static final String GLOBAL_ENTITY_ID = "globalEntityId";
    public static final String ADDRESSES = "addresses";

    private Long storeId;
    private String storeName;
    private String status;
    private String busEntityTypeCd;
    private Long globalEntityId;
    private Collection<AddressData> addresses = new ArrayList<AddressData>(0);

    public StoreListEntity() {
    }
	
    public StoreListEntity(Long storeId) {
        this.setStoreId(storeId);
    }

    public StoreListEntity(Long storeId, String storeName, String status, String busEntityTypeCd, Long globalEntityId, Collection<AddressData> addresses) {
        this.setStoreId(storeId);
        this.setStoreName(storeName);
        this.setStatus(status);
        this.setBusEntityTypeCd(busEntityTypeCd);
        this.setGlobalEntityId(globalEntityId);
        this.setAddresses(addresses);
    }

    @Id      
    @Column(name="BUS_ENTITY_ID", nullable=false)
    public Long getStoreId() {
        return this.storeId;
    }

    public void setStoreId(Long storeId) {
        this.storeId = storeId;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC")
    public String getStoreName() {
        return this.storeName;
    }

    public void setStoreName(String storeName) {
        this.storeName = storeName;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_STATUS_CD")
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_TYPE_CD")
    public String getBusEntityTypeCd() {
        return this.busEntityTypeCd;
    }

    public void setBusEntityTypeCd(String busEntityTypeCd) {
        this.busEntityTypeCd = busEntityTypeCd;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_ID", insertable=false, updatable=false)
    public Long getGlobalEntityId() {
        return this.globalEntityId;
    }

    public void setGlobalEntityId(Long globalEntityId) {
        this.globalEntityId = globalEntityId;
        setDirty(true);
    }

    @OneToMany(fetch=FetchType.EAGER)
    @JoinColumn(name="BUS_ENTITY_ID", updatable=false, columnDefinition="number")
    public Collection<AddressData> getAddresses() {
        return this.addresses;
    }

    public void setAddresses(Collection<AddressData> addresses) {
        this.addresses = addresses;
        setDirty(true);
    }




}


