package com.espendwise.manta.util;


public enum AccountIdentPropertyExtraCode implements PropertyExtraCode {

    INVENTORY_LEDGER_SWITCH (RefCodeNames.PROPERTY_TYPE_CD.INVENTORY_LEDGER_SWITCH),
    SCHEDULE_CUTOFF_DAYS (RefCodeNames.PROPERTY_TYPE_CD.SCHEDULE_CUTOFF_DAYS),
    INVENTORY_OG_LIST_UI (RefCodeNames.PROPERTY_TYPE_CD.INVENTORY_OG_LIST_UI),
    INVENTORY_MISSING_NOTIFICATION (RefCodeNames.PROPERTY_TYPE_CD.INVENTORY_MISSING_NOTIFICATION),
    INVENTORY_CHECK_PLACED_ORDER (RefCodeNames.PROPERTY_TYPE_CD.INVENTORY_CHECK_PLACED_ORDER),
    CONNECTION_CUSTOMER (RefCodeNames.PROPERTY_TYPE_CD.CONNECTION_CUSTOMER),
    CART_REMINDER_INTERVAL(RefCodeNames.PROPERTY_TYPE_CD.CART_REMINDER_INTERVAL),
    SHOW_SCHED_DELIVERY (RefCodeNames.PROPERTY_TYPE_CD.SHOW_SCHED_DELIVERY),
    ALLOW_ORDER_CONSOLIDATION (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_ORDER_CONSOLIDATION),
    SHOW_DIST_SKU_NUM (RefCodeNames.PROPERTY_TYPE_CD. SHOW_DIST_SKU_NUM),
    SHOW_DIST_DELIVERY_DATE (RefCodeNames.PROPERTY_TYPE_CD.SHOW_DIST_DELIVERY_DATE),
    RUSH_ORDER_CHARGE (RefCodeNames.PROPERTY_TYPE_CD.RUSH_ORDER_CHARGE),
    AUTO_ORDER_FACTOR (RefCodeNames.PROPERTY_TYPE_CD.AUTO_ORDER_FACTOR),
    DIST_INVENTORY_DISPLAY (RefCodeNames.PROPERTY_TYPE_CD.DIST_INVENTORY_DISPLAY),
    SHOW_SPL (RefCodeNames.PROPERTY_TYPE_CD.SHOW_SPL),
    ADD_SERVICE_FEE (RefCodeNames.PROPERTY_TYPE_CD.ADD_SERVICE_FEE),
    HOLD_PO (RefCodeNames.PROPERTY_TYPE_CD.HOLD_PO),
    ALLOW_USER_CHANGE_PASSWORD (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_USER_CHANGE_PASSWORD),
    ACCOUNT_FOLDER (RefCodeNames.PROPERTY_TYPE_CD.ACCOUNT_FOLDER),
    ACCOUNT_FOLDER_NEW (RefCodeNames.PROPERTY_TYPE_CD.ACCOUNT_FOLDER_NEW),
    ADJUST_QTY_BY_855 (RefCodeNames.PROPERTY_TYPE_CD.ADJUST_QTY_BY_855),
    CREATE_ORDER_BY_855 (RefCodeNames.PROPERTY_TYPE_CD.CREATE_ORDER_BY_855),
    CREATE_ORDER_ITEMS_BY_855 (RefCodeNames.PROPERTY_TYPE_CD.CREATE_ORDER_ITEMS_BY_855),
    MODIFY_CUST_PO_NUM_BY_855 (RefCodeNames.PROPERTY_TYPE_CD.MODIFY_CUST_PO_NUM_BY_855),
    SUPPORTS_BUDGET (RefCodeNames.PROPERTY_TYPE_CD.SUPPORTS_BUDGET),
    ALLOW_MODERN_SHOPPING (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_MODERN_SHOPPING),
    NOT_APP_TO_BUDGET_FOR_BT_ORDER (RefCodeNames.PROPERTY_TYPE_CD.NOT_APP_TO_BUDGET_FOR_BT_ORDER),
    SEND_ORDER_CONFRM_FOR_BT_ORDER (RefCodeNames.PROPERTY_TYPE_CD.SEND_ORDER_CONFRM_FOR_BT_ORDER),
    ALLOW_SITE_LLC (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_SITE_LLC),
    SHOW_EXPRESS_ORDER (RefCodeNames.PROPERTY_TYPE_CD.SHOW_EXPRESS_ORDER),
    ALLOW_ORDER_INV_ITEMS (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_ORDER_INV_ITEMS),
    ALLOW_REORDER (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_REORDER),
    USE_PHYSICAL_INVENTORY (RefCodeNames.PROPERTY_TYPE_CD.USE_PHYSICAL_INVENTORY),
    SHOW_INV_CART_TOTAL (RefCodeNames.PROPERTY_TYPE_CD.SHOW_INV_CART_TOTAL ),
    SHOW_MY_SHOPPING_LISTS (RefCodeNames.PROPERTY_TYPE_CD.SHOW_MY_SHOPPING_LISTS ),
    SHOW_REBILL_ORDER (RefCodeNames.PROPERTY_TYPE_CD.SHOW_REBILL_ORDER),
    ALLOW_SET_WORKORDER_PO_NUMBER (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_SET_WORKORDER_PO_NUMBER),
    USER_ASSIGNED_ASSET_NUMBER (RefCodeNames.PROPERTY_TYPE_CD.USER_ASSIGNED_ASSET_NUMBER),
    ALLOW_BUY_WORK_ORDER_PARTS (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_BUY_WORK_ORDER_PARTS),
    CONTACT_INFORMATION_TYPE (RefCodeNames.PROPERTY_TYPE_CD.CONTACT_INFORMATION_TYPE),
    WORK_ORDER_PO_NUM_REQUIRED (RefCodeNames.PROPERTY_TYPE_CD.WORK_ORDER_PO_NUM_REQUIRED),
    SHOP_UI_TYPE (RefCodeNames.PROPERTY_TYPE_CD.SHOP_UI_TYPE),
    FAQ_LINK (RefCodeNames.PROPERTY_TYPE_CD.FAQ_LINK),
    REMINDER_EMAIL_SUBJECT (RefCodeNames.PROPERTY_TYPE_CD.REMINDER_EMAIL_SUBJECT),
    REMINDER_EMAIL_MSG (RefCodeNames.PROPERTY_TYPE_CD.REMINDER_EMAIL_MSG ),
    NOTIFY_ORDER_EMAIL_GENERATOR (RefCodeNames.PROPERTY_TYPE_CD.NOTIFY_ORDER_EMAIL_GENERATOR),
    PENDING_APPROV_EMAIL_GENERATOR (RefCodeNames.PROPERTY_TYPE_CD.PENDING_APPROV_EMAIL_GENERATOR),
    REJECT_ORDER_EMAIL_GENERATOR (RefCodeNames.PROPERTY_TYPE_CD.REJECT_ORDER_EMAIL_GENERATOR),
    CONFIRM_ORDER_EMAIL_GENERATOR (RefCodeNames.PROPERTY_TYPE_CD.CONFIRM_ORDER_EMAIL_GENERATOR),
    ORDER_CONFIRMATION_EMAIL_TEMPLATE (RefCodeNames.PROPERTY_TYPE_CD.ORDER_CONFIRMATION_EMAIL_TEMPLATE),
    SHIPPING_NOTIFICATION_EMAIL_TEMPLATE (RefCodeNames.PROPERTY_TYPE_CD.SHIPPING_NOTIFICATION_EMAIL_TEMPLATE),
    PENDING_APPROVAL_EMAIL_TEMPLATE (RefCodeNames.PROPERTY_TYPE_CD.PENDING_APPROVAL_EMAIL_TEMPLATE),
    REJECTED_ORDER_EMAIL_TEMPLATE (RefCodeNames.PROPERTY_TYPE_CD.REJECTED_ORDER_EMAIL_TEMPLATE),
    MODIFIED_ORDER_EMAIL_TEMPLATE (RefCodeNames.PROPERTY_TYPE_CD.MODIFIED_ORDER_EMAIL_TEMPLATE),
    CONTACT_US_CC_ADD (RefCodeNames.PROPERTY_TYPE_CD.CONTACT_US_CC_ADD),
    PDF_ORDER_CLASS(RefCodeNames.PROPERTY_TYPE_CD.PDF_ORDER_CLASS),
    PDF_ORDER_STATUS_CLASS(RefCodeNames.PROPERTY_TYPE_CD.PDF_ORDER_STATUS_CLASS),
    ALLOW_CC_PAYMENT  (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_CC_PAYMENT ),
    ALLOW_ALTERNATE_SHIP_TO_ADDRESS (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_ALTERNATE_SHIP_TO_ADDRESS),
    INVENTORY_PO_SUFFIX(RefCodeNames.PROPERTY_TYPE_CD.INVENTORY_PO_SUFFIX);

    private String nameExtraCode;

    AccountIdentPropertyExtraCode(String NameExtraCode) {
        this.nameExtraCode = NameExtraCode;
    }

    public String getNameExtraCode() {
        return nameExtraCode;
    }
}
