package com.espendwise.manta.util;


public enum AccountIdentPropertyTypeCode implements PropertyTypeCode {

    DIST_ACCT_REF_NUM(RefCodeNames.PROPERTY_TYPE_CD.DIST_ACCT_REF_NUM),
    ACCOUNT_TYPE(RefCodeNames.PROPERTY_TYPE_CD.ACCOUNT_TYPE),
    BUDGET_ACCRUAL_TYPE_CD(RefCodeNames.PROPERTY_TYPE_CD.BUDGET_ACCRUAL_TYPE_CD),
    //default account property
    ALLOWED_RUNTIME_ORD_ITM_ACT(RefCodeNames.PROPERTY_TYPE_CD.ALLOWED_RUNTIME_ORD_ITM_ACT),
    ALLOW_CUSTOMER_PO_NUMBER (RefCodeNames.PROPERTY_TYPE_CD.ALLOW_CUSTOMER_PO_NUMBER),
    AUTHORIZED_FOR_RESALE (RefCodeNames.PROPERTY_TYPE_CD.AUTHORIZED_FOR_RESALE),
    COMMENTS (RefCodeNames.PROPERTY_TYPE_CD.COMMENTS),
    CRC_SHOP (RefCodeNames.PROPERTY_TYPE_CD.CRC_SHOP),
    CREDIT_LIMIT (RefCodeNames.PROPERTY_TYPE_CD.CREDIT_LIMIT),
    CREDIT_RATING (RefCodeNames.PROPERTY_TYPE_CD.CREDIT_RATING),
    CUSTOMER_SYSTEM_APPROVAL_CD (RefCodeNames.PROPERTY_TYPE_CD.CUSTOMER_SYSTEM_APPROVAL_CD),
    TRACK_PUNCHOUT_ORDER_MESSAGES (RefCodeNames.PROPERTY_TYPE_CD.TRACK_PUNCHOUT_ORDER_MESSAGES),
    DISTR_PO_TYPE (RefCodeNames.PROPERTY_TYPE_CD.DISTR_PO_TYPE), 
    FREIGHT_CHARGE_TYPE (RefCodeNames.PROPERTY_TYPE_CD.FREIGHT_CHARGE_TYPE ),
    GL_TRANSFORMATION_TYPE (RefCodeNames.PROPERTY_TYPE_CD.GL_TRANSFORMATION_TYPE),
    MAKE_SHIP_TO_BILL_TO (RefCodeNames.PROPERTY_TYPE_CD.MAKE_SHIP_TO_BILL_TO ),
    ORDER_MINIMUM (RefCodeNames.PROPERTY_TYPE_CD.ORDER_MINIMUM),
    ORDER_GUIDE_NOTE (RefCodeNames.PROPERTY_TYPE_CD.ORDER_GUIDE_NOTE),
    PURCHASE_ORDER_ACCOUNT_NAME (RefCodeNames.PROPERTY_TYPE_CD.PURCHASE_ORDER_ACCOUNT_NAME),
    RESALE_ACCOUNT_ERP_NUM (RefCodeNames.PROPERTY_TYPE_CD.RESALE_ACCOUNT_ERP_NUM ),
    SKU_TAG (RefCodeNames.PROPERTY_TYPE_CD.SKU_TAG),
    TARGET_MARGIN (RefCodeNames.PROPERTY_TYPE_CD.TARGET_MARGIN),
    USE_ALTERNATE_UI (RefCodeNames.PROPERTY_TYPE_CD.ALTERNATE_UI),
    TAXABLE_INDICATOR (RefCodeNames.PROPERTY_TYPE_CD.TAXABLE_INDICATOR) ;

    private String propertyTypeCode;

    AccountIdentPropertyTypeCode(String propertyTypeCode) {
        this.propertyTypeCode = propertyTypeCode;
    }

    @Override
    public String getTypeCode() {
        return propertyTypeCode;
    }

    @Override
    public String toString() {
        return propertyTypeCode;
    }

}
