package com.espendwise.manta.util;


public enum DistributorPropertyTypeCode implements PropertyTypeCode {

	RUNTIME_DISPLAY_NAME(RefCodeNames.PROPERTY_TYPE_CD.RUNTIME_DISPLAY_NAME),
	CALL_HOURS(RefCodeNames.PROPERTY_TYPE_CD.CALL_HOURS),
	DISTRIBUTORS_COMPANY_CODE(RefCodeNames.PROPERTY_TYPE_CD.DISTRIBUTORS_COMPANY_CODE),
	CUSTOMER_REFERENCE_CODE(RefCodeNames.PROPERTY_TYPE_CD.CUSTOMER_REFERENCE_CODE),
	DIST_MAX_INVOICE_FREIGHT(RefCodeNames.PROPERTY_TYPE_CD.DIST_MAX_INVOICE_FREIGHT),
	EXCEPTION_ON_TAX_DIFFERENCE(RefCodeNames.PROPERTY_TYPE_CD.EXCEPTION_ON_TAX_DIFFERENCE),
	HOLD_INVOICE(RefCodeNames.PROPERTY_TYPE_CD.HOLD_INVOICE),
	IGNORE_ORDER_MIN_FOR_FREIGHT(RefCodeNames.PROPERTY_TYPE_CD.IGNORE_ORDER_MIN_FOR_FREIGHT),
	INVOICE_AMT_PERCNT_ALLOW_UPPER(RefCodeNames.PROPERTY_TYPE_CD.INVOICE_AMT_PERCNT_ALLOW_UPPER),
	INVOICE_AMT_PERCNT_ALLOW_LOWER(RefCodeNames.PROPERTY_TYPE_CD.INVOICE_AMT_PERCNT_ALLOW_LOWER),
	INVOICE_LOADING_PRICE_MODEL_CD(RefCodeNames.PROPERTY_TYPE_CD.INVOICE_LOADING_PRICE_MODEL_CD),
	RECEIVING_SYSTEM_INVOICE_CD(RefCodeNames.PROPERTY_TYPE_CD.RECEIVING_SYSTEM_INVOICE_CD),
	ERROR_ON_OVERCHARGED_FREIGHT(RefCodeNames.PROPERTY_TYPE_CD.ERROR_ON_OVERCHARGED_FREIGHT),
	ALLOW_FREIGHT_ON_BACKORDERS(RefCodeNames.PROPERTY_TYPE_CD.ALLOW_FREIGHT_ON_BACKORDERS),
	PURCHASE_ORDER_COMMENTS(RefCodeNames.PROPERTY_TYPE_CD.PURCHASE_ORDER_COMMENTS),
	PRINT_CUST_CONTACT_ON_PO(RefCodeNames.PROPERTY_TYPE_CD.PRINT_CUST_CONTACT_ON_PO),
	MAN_PO_ACK_REQUIERED(RefCodeNames.PROPERTY_TYPE_CD.MAN_PO_ACK_REQUIERED),
	CANCEL_BACKORDERED_LINES(RefCodeNames.PROPERTY_TYPE_CD.CANCEL_BACKORDERED_LINES),
	DO_NOT_ALLOW_INVOICE_EDITS(RefCodeNames.PROPERTY_TYPE_CD.DO_NOT_ALLOW_INVOICE_EDITS);

    private String propertyTypeCode;

    DistributorPropertyTypeCode(String propertyTypeCode) {
        this.propertyTypeCode = propertyTypeCode;
    }

    @Override
    public String getTypeCode() {
        return propertyTypeCode;
    }

    @Override
    public String toString() {
        return propertyTypeCode;
    }

}
