package com.espendwise.manta.util;


public enum SitePropertyTypeCode implements PropertyTypeCode {

    ALLOW_CORPORATE_SCHED_ORDER(RefCodeNames.PROPERTY_TYPE_CD.ALLOW_CORPORATE_SCHED_ORDER),
    SHOW_REBILL_ORDER(RefCodeNames.PROPERTY_TYPE_CD.SHOW_REBILL_ORDER),
    BYPASS_ORDER_ROUTING(RefCodeNames.PROPERTY_TYPE_CD.BYPASS_ORDER_ROUTING),
    CONSOLIDATED_ORDER_WAREHOUSE(RefCodeNames.PROPERTY_TYPE_CD.CONSOLIDATED_ORDER_WAREHOUSE),
    INVENTORY_SHOPPING(RefCodeNames.PROPERTY_TYPE_CD.INVENTORY_SHOPPING),
    INVENTORY_SHOPPING_TYPE(RefCodeNames.PROPERTY_TYPE_CD.INVENTORY_SHOPPING_TYPE),
    TAXABLE_INDICATOR(RefCodeNames.PROPERTY_TYPE_CD.TAXABLE_INDICATOR),
    SITE_REFERENCE_NUMBER(RefCodeNames.PROPERTY_TYPE_CD.SITE_REFERENCE_NUMBER),
    DIST_SITE_REFERENCE_NUMBER(RefCodeNames.PROPERTY_TYPE_CD.DIST_SITE_REFERENCE_NUMBER),
    LOCATION_PRODUCT_BUNDLE(RefCodeNames.PROPERTY_TYPE_CD.LOCATION_PRODUCT_BUNDLE),
    LOCATION_LINE_LEVEL_CODE(RefCodeNames.PROPERTY_TYPE_CD.ALLOW_SITE_LLC),
    TARGET_FACILITY_RANK(RefCodeNames.PROPERTY_TYPE_CD.TARGET_FACILITY_RANK),
    LOCATION_COMMENTS(RefCodeNames.PROPERTY_TYPE_CD.LOCATION_COMMENTS),
    LOCATION_SHIP_MSG(RefCodeNames.PROPERTY_TYPE_CD.LOCATION_SHIP_MSG);

    private String propertyTypeCode;

    SitePropertyTypeCode(String propertyTypeCode) {
        this.propertyTypeCode = propertyTypeCode;
    }

    @Override
    public String getTypeCode() {
        return propertyTypeCode;
    }

    @Override
    public String toString() {
        return propertyTypeCode;
    }

}
