package com.espendwise.manta.web.resolver;

import com.espendwise.manta.util.validation.resolvers.AbstractDistributorConfigurationUpdateExceptionResolver;

public class DistributorConfigurationWebUpdateExceptionResolver extends AbstractDistributorConfigurationUpdateExceptionResolver {

}
