package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.BusEntityData;
/**
 * AccountIdentView generated by hbm2java
*/
public class AccountIdentView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUS_ENTITY_DATA = "busEntityData";
    public static final String ACCOUNT_CONTACT = "accountContact";
    public static final String PROPERTIES = "properties";

    private BusEntityData busEntityData;
    private AccountContactView accountContact;
    private AccountIdentPropertiesView properties;

    public AccountIdentView() {
    }
	
    public AccountIdentView(BusEntityData busEntityData) {
        this.setBusEntityData(busEntityData);
    }

    public AccountIdentView(BusEntityData busEntityData, AccountContactView accountContact, AccountIdentPropertiesView properties) {
        this.setBusEntityData(busEntityData);
        this.setAccountContact(accountContact);
        this.setProperties(properties);
    }

    public BusEntityData getBusEntityData() {
        return this.busEntityData;
    }

    public void setBusEntityData(BusEntityData busEntityData) {
        this.busEntityData = busEntityData;
        setDirty(true);
    }

    public AccountContactView getAccountContact() {
        return this.accountContact;
    }

    public void setAccountContact(AccountContactView accountContact) {
        this.accountContact = accountContact;
        setDirty(true);
    }

    public AccountIdentPropertiesView getProperties() {
        return this.properties;
    }

    public void setProperties(AccountIdentPropertiesView properties) {
        this.properties = properties;
        setDirty(true);
    }




}


