package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * AccountListView generated by hbm2java
*/
public class AccountListView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String ACCOUNT_ID = "accountId";
    public static final String ACCOUNT_NAME = "accountName";
    public static final String TYPE = "type";
    public static final String STATUS = "status";
    public static final String BILLING_ADDRESS1 = "billingAddress1";
    public static final String BILLING_CITY = "billingCity";
    public static final String BILLING_STATE = "billingState";
    public static final String REF_NUMBER = "refNumber";

    private Long accountId;
    private String accountName;
    private String type;
    private String status;
    private String billingAddress1;
    private String billingCity;
    private String billingState;
    private String refNumber;

    public AccountListView() {
    }
	
    public AccountListView(Long accountId) {
        this.setAccountId(accountId);
    }

    public AccountListView(Long accountId, String accountName, String type, String status, String billingAddress1, String billingCity, String billingState, String refNumber) {
        this.setAccountId(accountId);
        this.setAccountName(accountName);
        this.setType(type);
        this.setStatus(status);
        this.setBillingAddress1(billingAddress1);
        this.setBillingCity(billingCity);
        this.setBillingState(billingState);
        this.setRefNumber(refNumber);
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
        setDirty(true);
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
        setDirty(true);
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
        setDirty(true);
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
        setDirty(true);
    }

    public String getBillingAddress1() {
        return this.billingAddress1;
    }

    public void setBillingAddress1(String billingAddress1) {
        this.billingAddress1 = billingAddress1;
        setDirty(true);
    }

    public String getBillingCity() {
        return this.billingCity;
    }

    public void setBillingCity(String billingCity) {
        this.billingCity = billingCity;
        setDirty(true);
    }

    public String getBillingState() {
        return this.billingState;
    }

    public void setBillingState(String billingState) {
        this.billingState = billingState;
        setDirty(true);
    }

    public String getRefNumber() {
        return this.refNumber;
    }

    public void setRefNumber(String refNumber) {
        this.refNumber = refNumber;
        setDirty(true);
    }




}


