package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.AllUserData;
import com.espendwise.manta.model.data.UserStoreData;
import java.util.List;
/**
 * AllUserIdentView generated by hbm2java
*/
public class AllUserIdentView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String ALL_USER_DATA = "allUserData";
    public static final String USER_STORE_ASSOC = "userStoreAssoc";

    private AllUserData allUserData;
    private List<UserStoreData> userStoreAssoc;

    public AllUserIdentView() {
    }
	
    public AllUserIdentView(AllUserData allUserData) {
        this.setAllUserData(allUserData);
    }

    public AllUserIdentView(AllUserData allUserData, List<UserStoreData> userStoreAssoc) {
        this.setAllUserData(allUserData);
        this.setUserStoreAssoc(userStoreAssoc);
    }

    public AllUserData getAllUserData() {
        return this.allUserData;
    }

    public void setAllUserData(AllUserData allUserData) {
        this.allUserData = allUserData;
        setDirty(true);
    }

    public List<UserStoreData> getUserStoreAssoc() {
        return this.userStoreAssoc;
    }

    public void setUserStoreAssoc(List<UserStoreData> userStoreAssoc) {
        this.userStoreAssoc = userStoreAssoc;
        setDirty(true);
    }




}


