package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.BudgetData;
import com.espendwise.manta.model.data.BudgetDetailData;
import java.util.Collection;
/**
 * BudgetView generated by hbm2java
*/
public class BudgetView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUDGET_DATA = "budgetData";
    public static final String BUDGET_DETAILS = "budgetDetails";

    private BudgetData budgetData;
    private Collection<BudgetDetailData> budgetDetails;

    public BudgetView() {
    }
	
    public BudgetView(BudgetData budgetData) {
        this.setBudgetData(budgetData);
    }

    public BudgetView(BudgetData budgetData, Collection<BudgetDetailData> budgetDetails) {
        this.setBudgetData(budgetData);
        this.setBudgetDetails(budgetDetails);
    }

    public BudgetData getBudgetData() {
        return this.budgetData;
    }

    public void setBudgetData(BudgetData budgetData) {
        this.budgetData = budgetData;
        setDirty(true);
    }

    public Collection<BudgetDetailData> getBudgetDetails() {
        return this.budgetDetails;
    }

    public void setBudgetDetails(Collection<BudgetDetailData> budgetDetails) {
        this.budgetDetails = budgetDetails;
        setDirty(true);
    }




}


