package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * CatalogListView generated by hbm2java
*/
public class CatalogListView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String CATALOG_ID = "catalogId";
    public static final String CATALOG_NAME = "catalogName";
    public static final String TYPE = "type";
    public static final String STATUS = "status";

    private Long catalogId;
    private String catalogName;
    private String type;
    private String status;

    public CatalogListView() {
    }
	
    public CatalogListView(Long catalogId) {
        this.setCatalogId(catalogId);
    }

    public CatalogListView(Long catalogId, String catalogName, String type, String status) {
        this.setCatalogId(catalogId);
        this.setCatalogName(catalogName);
        this.setType(type);
        this.setStatus(status);
    }

    public Long getCatalogId() {
        return this.catalogId;
    }

    public void setCatalogId(Long catalogId) {
        this.catalogId = catalogId;
        setDirty(true);
    }

    public String getCatalogName() {
        return this.catalogName;
    }

    public void setCatalogName(String catalogName) {
        this.catalogName = catalogName;
        setDirty(true);
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
        setDirty(true);
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
        setDirty(true);
    }




}


