package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * CMSView generated by hbm2java
*/
public class CMSView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String PRIMARY_ENTITY_ID = "primaryEntityId";
    public static final String PRIMARY_ENTITY_NAME = "primaryEntityName";
    public static final String CONTENT_MANAGEMENT_PROPERTIES = "contentManagementProperties";

    private Long primaryEntityId;
    private String primaryEntityName;
    private ContentManagementView contentManagementProperties;

    public CMSView() {
    }
	
    public CMSView(Long primaryEntityId) {
        this.setPrimaryEntityId(primaryEntityId);
    }

    public CMSView(Long primaryEntityId, String primaryEntityName, ContentManagementView contentManagementProperties) {
        this.setPrimaryEntityId(primaryEntityId);
        this.setPrimaryEntityName(primaryEntityName);
        this.setContentManagementProperties(contentManagementProperties);
    }

    public Long getPrimaryEntityId() {
        return this.primaryEntityId;
    }

    public void setPrimaryEntityId(Long primaryEntityId) {
        this.primaryEntityId = primaryEntityId;
        setDirty(true);
    }

    public String getPrimaryEntityName() {
        return this.primaryEntityName;
    }

    public void setPrimaryEntityName(String primaryEntityName) {
        this.primaryEntityName = primaryEntityName;
        setDirty(true);
    }

    public ContentManagementView getContentManagementProperties() {
        return this.contentManagementProperties;
    }

    public void setContentManagementProperties(ContentManagementView contentManagementProperties) {
        this.contentManagementProperties = contentManagementProperties;
        setDirty(true);
    }




}


