package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.PropertyData;
/**
 * ContentManagementView generated by hbm2java
*/
public class ContentManagementView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String DISPLAY_GENERIC_CONTENT = "displayGenericContent";
    public static final String CUSTOM_CONTENT_U_R_L = "customContentURL";
    public static final String CUSTOM_CONTENT_EDITOR = "customContentEditor";
    public static final String CUSTOM_CONTENT_VIEWER = "customContentViewer";

    private Long busEntityId;
    private PropertyData displayGenericContent;
    private PropertyData customContentURL;
    private PropertyData customContentEditor;
    private PropertyData customContentViewer;

    public ContentManagementView() {
    }
	
    public ContentManagementView(Long busEntityId) {
        this.setBusEntityId(busEntityId);
    }

    public ContentManagementView(Long busEntityId, PropertyData displayGenericContent, PropertyData customContentURL, PropertyData customContentEditor, PropertyData customContentViewer) {
        this.setBusEntityId(busEntityId);
        this.setDisplayGenericContent(displayGenericContent);
        this.setCustomContentURL(customContentURL);
        this.setCustomContentEditor(customContentEditor);
        this.setCustomContentViewer(customContentViewer);
    }

    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    public PropertyData getDisplayGenericContent() {
        return this.displayGenericContent;
    }

    public void setDisplayGenericContent(PropertyData displayGenericContent) {
        this.displayGenericContent = displayGenericContent;
        setDirty(true);
    }

    public PropertyData getCustomContentURL() {
        return this.customContentURL;
    }

    public void setCustomContentURL(PropertyData customContentURL) {
        this.customContentURL = customContentURL;
        setDirty(true);
    }

    public PropertyData getCustomContentEditor() {
        return this.customContentEditor;
    }

    public void setCustomContentEditor(PropertyData customContentEditor) {
        this.customContentEditor = customContentEditor;
        setDirty(true);
    }

    public PropertyData getCustomContentViewer() {
        return this.customContentViewer;
    }

    public void setCustomContentViewer(PropertyData customContentViewer) {
        this.customContentViewer = customContentViewer;
        setDirty(true);
    }




}


