package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.CostCenterData;
import java.util.List;
/**
 * CostCenterView generated by hbm2java
*/
public class CostCenterView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String COST_CENTER_DATA = "costCenterData";

    private CostCenterData costCenterData;

    public CostCenterView() {
    }

    public CostCenterView(CostCenterData costCenterData) {
        this.setCostCenterData(costCenterData);
    }

    public CostCenterData getCostCenterData() {
        return this.costCenterData;
    }

    public void setCostCenterData(CostCenterData costCenterData) {
        this.costCenterData = costCenterData;
        setDirty(true);
    }




}


