package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * CostCenterListView generated by hbm2java
*/
public class CostCenterListView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String COST_CENTER_ID = "costCenterId";
    public static final String COST_CENTER_NAME = "costCenterName";
    public static final String COST_CENTER_TYPE = "costCenterType";
    public static final String STATUS = "status";
    public static final String TAX_TYPE = "taxType";
    public static final String ALLOCATE_FREIGHT = "allocateFreight";
    public static final String ALLOCATE_DISCOUNT = "allocateDiscount";

    private Long costCenterId;
    private String costCenterName;
    private String costCenterType;
    private String status;
    private String taxType;
    private String allocateFreight;
    private String allocateDiscount;

    public CostCenterListView() {
    }
	
    public CostCenterListView(Long costCenterId) {
        this.setCostCenterId(costCenterId);
    }

    public CostCenterListView(Long costCenterId, String costCenterName, String costCenterType, String status, String taxType, String allocateFreight, String allocateDiscount) {
        this.setCostCenterId(costCenterId);
        this.setCostCenterName(costCenterName);
        this.setCostCenterType(costCenterType);
        this.setStatus(status);
        this.setTaxType(taxType);
        this.setAllocateFreight(allocateFreight);
        this.setAllocateDiscount(allocateDiscount);
    }

    public Long getCostCenterId() {
        return this.costCenterId;
    }

    public void setCostCenterId(Long costCenterId) {
        this.costCenterId = costCenterId;
        setDirty(true);
    }

    public String getCostCenterName() {
        return this.costCenterName;
    }

    public void setCostCenterName(String costCenterName) {
        this.costCenterName = costCenterName;
        setDirty(true);
    }

    public String getCostCenterType() {
        return this.costCenterType;
    }

    public void setCostCenterType(String costCenterType) {
        this.costCenterType = costCenterType;
        setDirty(true);
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
        setDirty(true);
    }

    public String getTaxType() {
        return this.taxType;
    }

    public void setTaxType(String taxType) {
        this.taxType = taxType;
        setDirty(true);
    }

    public String getAllocateFreight() {
        return this.allocateFreight;
    }

    public void setAllocateFreight(String allocateFreight) {
        this.allocateFreight = allocateFreight;
        setDirty(true);
    }

    public String getAllocateDiscount() {
        return this.allocateDiscount;
    }

    public void setAllocateDiscount(String allocateDiscount) {
        this.allocateDiscount = allocateDiscount;
        setDirty(true);
    }




}


