package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * CostCenterHeaderView generated by hbm2java
*/
public class CostCenterHeaderView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String COST_CENTER_ID = "costCenterId";
    public static final String COST_CENTER_NAME = "costCenterName";

    private Long costCenterId;
    private String costCenterName;

    public CostCenterHeaderView() {
    }
	
    public CostCenterHeaderView(Long costCenterId) {
        this.setCostCenterId(costCenterId);
    }

    public CostCenterHeaderView(Long costCenterId, String costCenterName) {
        this.setCostCenterId(costCenterId);
        this.setCostCenterName(costCenterName);
    }

    public Long getCostCenterId() {
        return this.costCenterId;
    }

    public void setCostCenterId(Long costCenterId) {
        this.costCenterId = costCenterId;
        setDirty(true);
    }

    public String getCostCenterName() {
        return this.costCenterName;
    }

    public void setCostCenterName(String costCenterName) {
        this.costCenterName = costCenterName;
        setDirty(true);
    }




}


