package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * DisplaySettingsView generated by hbm2java
*/
public class DisplaySettingsView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String WIDE_SCREEN = "wideScreen";

    private String wideScreen;

    public DisplaySettingsView() {
    }

    public DisplaySettingsView(String wideScreen) {
        this.setWideScreen(wideScreen);
    }

    public String getWideScreen() {
        return this.wideScreen;
    }

    public void setWideScreen(String wideScreen) {
        this.wideScreen = wideScreen;
        setDirty(true);
    }




}


