package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.TemplateData;
import com.espendwise.manta.model.data.TemplatePropertyData;
import java.util.List;
/**
 * EmailTemplateIdentView generated by hbm2java
*/
public class EmailTemplateIdentView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String TEMPLATE_DATA = "templateData";
    public static final String PROPERTIES = "properties";

    private TemplateData templateData;
    private List<TemplatePropertyData> properties;

    public EmailTemplateIdentView() {
    }
	
    public EmailTemplateIdentView(TemplateData templateData) {
        this.setTemplateData(templateData);
    }

    public EmailTemplateIdentView(TemplateData templateData, List<TemplatePropertyData> properties) {
        this.setTemplateData(templateData);
        this.setProperties(properties);
    }

    public TemplateData getTemplateData() {
        return this.templateData;
    }

    public void setTemplateData(TemplateData templateData) {
        this.templateData = templateData;
        setDirty(true);
    }

    public List<TemplatePropertyData> getProperties() {
        return this.properties;
    }

    public void setProperties(List<TemplatePropertyData> properties) {
        this.properties = properties;
        setDirty(true);
    }




}


