package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import java.util.Date;
/**
 * FiscalCalendarListView generated by hbm2java
*/
public class FiscalCalendarListView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String FISCAL_CALENDAR_ID = "fiscalCalendarId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String FISCAL_YEAR = "fiscalYear";
    public static final String NUM_OF_PERIODS = "numOfPeriods";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";

    private Long fiscalCalendarId;
    private Long busEntityId;
    private Integer fiscalYear;
    private Long numOfPeriods;
    private Date effDate;
    private Date expDate;

    public FiscalCalendarListView() {
    }
	
    public FiscalCalendarListView(Long fiscalCalendarId) {
        this.setFiscalCalendarId(fiscalCalendarId);
    }

    public FiscalCalendarListView(Long fiscalCalendarId, Long busEntityId, Integer fiscalYear, Long numOfPeriods, Date effDate, Date expDate) {
        this.setFiscalCalendarId(fiscalCalendarId);
        this.setBusEntityId(busEntityId);
        this.setFiscalYear(fiscalYear);
        this.setNumOfPeriods(numOfPeriods);
        this.setEffDate(effDate);
        this.setExpDate(expDate);
    }

    public Long getFiscalCalendarId() {
        return this.fiscalCalendarId;
    }

    public void setFiscalCalendarId(Long fiscalCalendarId) {
        this.fiscalCalendarId = fiscalCalendarId;
        setDirty(true);
    }

    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    public Integer getFiscalYear() {
        return this.fiscalYear;
    }

    public void setFiscalYear(Integer fiscalYear) {
        this.fiscalYear = fiscalYear;
        setDirty(true);
    }

    public Long getNumOfPeriods() {
        return this.numOfPeriods;
    }

    public void setNumOfPeriods(Long numOfPeriods) {
        this.numOfPeriods = numOfPeriods;
        setDirty(true);
    }

    public Date getEffDate() {
        return this.effDate;
    }

    public void setEffDate(Date effDate) {
        this.effDate = effDate;
        setDirty(true);
    }

    public Date getExpDate() {
        return this.expDate;
    }

    public void setExpDate(Date expDate) {
        this.expDate = expDate;
        setDirty(true);
    }




}


