package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.FiscalCalenderData;
import com.espendwise.manta.model.data.FiscalCalenderDetailData;
import java.util.Date;
import java.util.List;
/**
 * FiscalCalendarPhysicalView generated by hbm2java
*/
public class FiscalCalendarPhysicalView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String FISCAL_CALENDAR_ID = "fiscalCalendarId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String CALENDAT_FISCAL_YEAR = "calendatFiscalYear";
    public static final String PHYSICAL_FISCAL_YEAR = "physicalFiscalYear";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String PERIODS = "periods";
    public static final String SERVICE_SCHEDULE_CALENDAR = "serviceScheduleCalendar";

    private Long fiscalCalendarId;
    private Long busEntityId;
    private Integer calendatFiscalYear;
    private int physicalFiscalYear;
    private Date effDate;
    private Date expDate;
    private List<com.espendwise.manta.model.data.FiscalCalenderDetailData> periods;
    private boolean serviceScheduleCalendar;

    public FiscalCalendarPhysicalView() {
    }
	
    public FiscalCalendarPhysicalView(Long fiscalCalendarId) {
        this.setFiscalCalendarId(fiscalCalendarId);
    }

    public FiscalCalendarPhysicalView(Long fiscalCalendarId, Long busEntityId, Integer calendatFiscalYear, int physicalFiscalYear, Date effDate, Date expDate, List<com.espendwise.manta.model.data.FiscalCalenderDetailData> periods, boolean serviceScheduleCalendar) {
        this.setFiscalCalendarId(fiscalCalendarId);
        this.setBusEntityId(busEntityId);
        this.setCalendatFiscalYear(calendatFiscalYear);
        this.setPhysicalFiscalYear(physicalFiscalYear);
        this.setEffDate(effDate);
        this.setExpDate(expDate);
        this.setPeriods(periods);
        this.setServiceScheduleCalendar(serviceScheduleCalendar);
    }

    public Long getFiscalCalendarId() {
        return this.fiscalCalendarId;
    }

    public void setFiscalCalendarId(Long fiscalCalendarId) {
        this.fiscalCalendarId = fiscalCalendarId;
        setDirty(true);
    }

    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    public Integer getCalendatFiscalYear() {
        return this.calendatFiscalYear;
    }

    public void setCalendatFiscalYear(Integer calendatFiscalYear) {
        this.calendatFiscalYear = calendatFiscalYear;
        setDirty(true);
    }

    public int getPhysicalFiscalYear() {
        return this.physicalFiscalYear;
    }

    public void setPhysicalFiscalYear(int physicalFiscalYear) {
        this.physicalFiscalYear = physicalFiscalYear;
        setDirty(true);
    }

    public Date getEffDate() {
        return this.effDate;
    }

    public void setEffDate(Date effDate) {
        this.effDate = effDate;
        setDirty(true);
    }

    public Date getExpDate() {
        return this.expDate;
    }

    public void setExpDate(Date expDate) {
        this.expDate = expDate;
        setDirty(true);
    }

    public List<com.espendwise.manta.model.data.FiscalCalenderDetailData> getPeriods() {
        return this.periods;
    }

    public void setPeriods(List<com.espendwise.manta.model.data.FiscalCalenderDetailData> periods) {
        this.periods = periods;
        setDirty(true);
    }

    public boolean isServiceScheduleCalendar() {
        return this.serviceScheduleCalendar;
    }

    public void setServiceScheduleCalendar(boolean serviceScheduleCalendar) {
        this.serviceScheduleCalendar = serviceScheduleCalendar;
        setDirty(true);
    }




}


