package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import java.util.Date;
/**
 * FiscalReportIntersectResView generated by hbm2java
*/
public class FiscalReportIntersectResView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String MMDD = "mmdd";
    public static final String EFF_DATE = "effDate";
    public static final String FISCAL_YEAR = "fiscalYear";

    private Long busEntityId;
    private String mmdd;
    private Date effDate;
    private int fiscalYear;

    public FiscalReportIntersectResView() {
    }
	
    public FiscalReportIntersectResView(Long busEntityId) {
        this.setBusEntityId(busEntityId);
    }

    public FiscalReportIntersectResView(Long busEntityId, String mmdd, Date effDate, int fiscalYear) {
        this.setBusEntityId(busEntityId);
        this.setMmdd(mmdd);
        this.setEffDate(effDate);
        this.setFiscalYear(fiscalYear);
    }

    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    public String getMmdd() {
        return this.mmdd;
    }

    public void setMmdd(String mmdd) {
        this.mmdd = mmdd;
        setDirty(true);
    }

    public Date getEffDate() {
        return this.effDate;
    }

    public void setEffDate(Date effDate) {
        this.effDate = effDate;
        setDirty(true);
    }

    public int getFiscalYear() {
        return this.fiscalYear;
    }

    public void setFiscalYear(int fiscalYear) {
        this.fiscalYear = fiscalYear;
        setDirty(true);
    }




}


