package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import java.util.List;
/**
 * GenericReportColumnView generated by hbm2java
*/
public class GenericReportColumnView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String COLUMN_NAME = "columnName";
    public static final String COLUMN_CLASS = "columnClass";
    public static final String COLUMN_TYPE = "columnType";
    public static final String COLUMN_PRECISION = "columnPrecision";
    public static final String COLUMN_SCALE = "columnScale";
    public static final String COLUMN_WIDTH = "columnWidth";
    public static final String TOTAL_REQUEST_FLAG = "totalRequestFlag";
    public static final String COLUMN_FORMAT = "columnFormat";
    public static final String COLUMN_HEADER_STYLE_NAME = "columnHeaderStyleName";
    public static final String COLUMN_DATA_STYLE_NAME = "columnDataStyleName";

    private String columnName;
    private String columnClass;
    private String columnType;
    private int columnPrecision;
    private Integer columnScale;
    private String columnWidth;
    private boolean totalRequestFlag;
    private String columnFormat;
    private String columnHeaderStyleName;
    private String columnDataStyleName;

    public GenericReportColumnView() {
    }
	
    public GenericReportColumnView(String columnName) {
        this.setColumnName(columnName);
    }

    public GenericReportColumnView(String columnName, String columnClass, String columnType, int columnPrecision, Integer columnScale, String columnWidth, boolean totalRequestFlag, String columnFormat, String columnHeaderStyleName, String columnDataStyleName) {
        this.setColumnName(columnName);
        this.setColumnClass(columnClass);
        this.setColumnType(columnType);
        this.setColumnPrecision(columnPrecision);
        this.setColumnScale(columnScale);
        this.setColumnWidth(columnWidth);
        this.setTotalRequestFlag(totalRequestFlag);
        this.setColumnFormat(columnFormat);
        this.setColumnHeaderStyleName(columnHeaderStyleName);
        this.setColumnDataStyleName(columnDataStyleName);
    }

    public String getColumnName() {
        return this.columnName;
    }

    public void setColumnName(String columnName) {
        this.columnName = columnName;
        setDirty(true);
    }

    public String getColumnClass() {
        return this.columnClass;
    }

    public void setColumnClass(String columnClass) {
        this.columnClass = columnClass;
        setDirty(true);
    }

    public String getColumnType() {
        return this.columnType;
    }

    public void setColumnType(String columnType) {
        this.columnType = columnType;
        setDirty(true);
    }

    public int getColumnPrecision() {
        return this.columnPrecision;
    }

    public void setColumnPrecision(int columnPrecision) {
        this.columnPrecision = columnPrecision;
        setDirty(true);
    }

    public Integer getColumnScale() {
        return this.columnScale;
    }

    public void setColumnScale(Integer columnScale) {
        this.columnScale = columnScale;
        setDirty(true);
    }

    public String getColumnWidth() {
        return this.columnWidth;
    }

    public void setColumnWidth(String columnWidth) {
        this.columnWidth = columnWidth;
        setDirty(true);
    }

    public boolean isTotalRequestFlag() {
        return this.totalRequestFlag;
    }

    public void setTotalRequestFlag(boolean totalRequestFlag) {
        this.totalRequestFlag = totalRequestFlag;
        setDirty(true);
    }

    public String getColumnFormat() {
        return this.columnFormat;
    }

    public void setColumnFormat(String columnFormat) {
        this.columnFormat = columnFormat;
        setDirty(true);
    }

    public String getColumnHeaderStyleName() {
        return this.columnHeaderStyleName;
    }

    public void setColumnHeaderStyleName(String columnHeaderStyleName) {
        this.columnHeaderStyleName = columnHeaderStyleName;
        setDirty(true);
    }

    public String getColumnDataStyleName() {
        return this.columnDataStyleName;
    }

    public void setColumnDataStyleName(String columnDataStyleName) {
        this.columnDataStyleName = columnDataStyleName;
        setDirty(true);
    }




}


