package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * MainStoreIdentView generated by hbm2java
*/
public class MainStoreIdentView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String ID = "id";
    public static final String SHORT_DESC = "shortDesc";

    private Long id;
    private String shortDesc;

    public MainStoreIdentView() {
    }
	
    public MainStoreIdentView(Long id) {
        this.setId(id);
    }

    public MainStoreIdentView(Long id, String shortDesc) {
        this.setId(id);
        this.setShortDesc(shortDesc);
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
        setDirty(true);
    }

    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }




}


