package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * ManufacturerListView generated by hbm2java
*/
public class ManufacturerListView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String MANUFACTURER_ID = "manufacturerId";
    public static final String MANUFACTURER_NAME = "manufacturerName";
    public static final String STATUS = "status";

    private Long manufacturerId;
    private String manufacturerName;
    private String status;

    public ManufacturerListView() {
    }
	
    public ManufacturerListView(Long manufacturerId) {
        this.setManufacturerId(manufacturerId);
    }

    public ManufacturerListView(Long manufacturerId, String manufacturerName, String status) {
        this.setManufacturerId(manufacturerId);
        this.setManufacturerName(manufacturerName);
        this.setStatus(status);
    }

    public Long getManufacturerId() {
        return this.manufacturerId;
    }

    public void setManufacturerId(Long manufacturerId) {
        this.manufacturerId = manufacturerId;
        setDirty(true);
    }

    public String getManufacturerName() {
        return this.manufacturerName;
    }

    public void setManufacturerName(String manufacturerName) {
        this.manufacturerName = manufacturerName;
        setDirty(true);
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
        setDirty(true);
    }




}


