package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import java.util.Date;
/**
 * OrderListView generated by hbm2java
*/
public class OrderListView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String ORDER_ID = "orderId";
    public static final String ACCOUNT_NAME = "accountName";
    public static final String DIST_NAME = "distName";
    public static final String WEB_ORDER_NUM = "webOrderNum";
    public static final String ORIGINAL_ORDER_DATE = "originalOrderDate";
    public static final String REVISED_ORDER_DATE = "revisedOrderDate";
    public static final String CUSTOMER_PO_NUM = "customerPoNum";
    public static final String SITE_NAME = "siteName";
    public static final String ADDRESS1 = "address1";
    public static final String CITY = "city";
    public static final String STATE_PROVINCE = "stateProvince";
    public static final String POSTAL_CODE = "postalCode";
    public static final String ORDER_STATUS = "orderStatus";
    public static final String ORDER_SOURCE = "orderSource";
    public static final String PLACED_BY = "placedBy";

    private Long orderId;
    private String accountName;
    private String distName;
    private String webOrderNum;
    private Date originalOrderDate;
    private Date revisedOrderDate;
    private String customerPoNum;
    private String siteName;
    private String address1;
    private String city;
    private String stateProvince;
    private String postalCode;
    private String orderStatus;
    private String orderSource;
    private String placedBy;

    public OrderListView() {
    }
	
    public OrderListView(Long orderId) {
        this.setOrderId(orderId);
    }

    public OrderListView(Long orderId, String accountName, String distName, String webOrderNum, Date originalOrderDate, Date revisedOrderDate, String customerPoNum, String siteName, String address1, String city, String stateProvince, String postalCode, String orderStatus, String orderSource, String placedBy) {
        this.setOrderId(orderId);
        this.setAccountName(accountName);
        this.setDistName(distName);
        this.setWebOrderNum(webOrderNum);
        this.setOriginalOrderDate(originalOrderDate);
        this.setRevisedOrderDate(revisedOrderDate);
        this.setCustomerPoNum(customerPoNum);
        this.setSiteName(siteName);
        this.setAddress1(address1);
        this.setCity(city);
        this.setStateProvince(stateProvince);
        this.setPostalCode(postalCode);
        this.setOrderStatus(orderStatus);
        this.setOrderSource(orderSource);
        this.setPlacedBy(placedBy);
    }

    public Long getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Long orderId) {
        this.orderId = orderId;
        setDirty(true);
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
        setDirty(true);
    }

    public String getDistName() {
        return this.distName;
    }

    public void setDistName(String distName) {
        this.distName = distName;
        setDirty(true);
    }

    public String getWebOrderNum() {
        return this.webOrderNum;
    }

    public void setWebOrderNum(String webOrderNum) {
        this.webOrderNum = webOrderNum;
        setDirty(true);
    }

    public Date getOriginalOrderDate() {
        return this.originalOrderDate;
    }

    public void setOriginalOrderDate(Date originalOrderDate) {
        this.originalOrderDate = originalOrderDate;
        setDirty(true);
    }

    public Date getRevisedOrderDate() {
        return this.revisedOrderDate;
    }

    public void setRevisedOrderDate(Date revisedOrderDate) {
        this.revisedOrderDate = revisedOrderDate;
        setDirty(true);
    }

    public String getCustomerPoNum() {
        return this.customerPoNum;
    }

    public void setCustomerPoNum(String customerPoNum) {
        this.customerPoNum = customerPoNum;
        setDirty(true);
    }

    public String getSiteName() {
        return this.siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
        setDirty(true);
    }

    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
        setDirty(true);
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
        setDirty(true);
    }

    public String getStateProvince() {
        return this.stateProvince;
    }

    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince;
        setDirty(true);
    }

    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        setDirty(true);
    }

    public String getOrderStatus() {
        return this.orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
        setDirty(true);
    }

    public String getOrderSource() {
        return this.orderSource;
    }

    public void setOrderSource(String orderSource) {
        this.orderSource = orderSource;
        setDirty(true);
    }

    public String getPlacedBy() {
        return this.placedBy;
    }

    public void setPlacedBy(String placedBy) {
        this.placedBy = placedBy;
        setDirty(true);
    }




}


