package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.ScheduleData;
import com.espendwise.manta.model.data.ScheduleDetailData;
import java.util.List;
/**
 * ScheduleJoinView generated by hbm2java
*/
public class ScheduleJoinView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String SCHEDULE = "schedule";
    public static final String SCHEDULE_DETAIL = "scheduleDetail";

    private ScheduleData  schedule;
    private List<ScheduleDetailData> scheduleDetail;

    public ScheduleJoinView() {
    }
	
    public ScheduleJoinView(ScheduleData  schedule) {
        this.setSchedule(schedule);
    }

    public ScheduleJoinView(ScheduleData  schedule, List<ScheduleDetailData> scheduleDetail) {
        this.setSchedule(schedule);
        this.setScheduleDetail(scheduleDetail);
    }

    public ScheduleData  getSchedule() {
        return this.schedule;
    }

    public void setSchedule(ScheduleData  schedule) {
        this.schedule = schedule;
        setDirty(true);
    }

    public List<ScheduleDetailData> getScheduleDetail() {
        return this.scheduleDetail;
    }

    public void setScheduleDetail(List<ScheduleDetailData> scheduleDetail) {
        this.scheduleDetail = scheduleDetail;
        setDirty(true);
    }




}


