package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.util.PhysicalInventoryPeriod;
import java.util.Date;
import java.util.List;
/**
 * ScheduleOrderDatesView generated by hbm2java
*/
public class ScheduleOrderDatesView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String NEXT_ORDER_DELIVERY = "nextOrderDelivery";
    public static final String NEXT_ORDER_CUTOFF = "nextOrderCutoff";
    public static final String NEXT_ORDER_CUTOFF_TIME = "nextOrderCutoffTime";
    public static final String PHYSICAL_INVENTORY_PERIODS = "physicalInventoryPeriods";
    public static final String INVENTORY_CART_ACCESS_INTERVA = "inventoryCartAccessInterva";

    private Date nextOrderDelivery;
    private Date nextOrderCutoff;
    private Date nextOrderCutoffTime;
    private List<PhysicalInventoryPeriod> physicalInventoryPeriods;
    private String inventoryCartAccessInterva;

    public ScheduleOrderDatesView() {
    }
	
    public ScheduleOrderDatesView(Date nextOrderDelivery) {
        this.setNextOrderDelivery(nextOrderDelivery);
    }

    public ScheduleOrderDatesView(Date nextOrderDelivery, Date nextOrderCutoff, Date nextOrderCutoffTime, List<PhysicalInventoryPeriod> physicalInventoryPeriods, String inventoryCartAccessInterva) {
        this.setNextOrderDelivery(nextOrderDelivery);
        this.setNextOrderCutoff(nextOrderCutoff);
        this.setNextOrderCutoffTime(nextOrderCutoffTime);
        this.setPhysicalInventoryPeriods(physicalInventoryPeriods);
        this.setInventoryCartAccessInterva(inventoryCartAccessInterva);
    }

    public Date getNextOrderDelivery() {
        return this.nextOrderDelivery;
    }

    public void setNextOrderDelivery(Date nextOrderDelivery) {
        this.nextOrderDelivery = nextOrderDelivery;
        setDirty(true);
    }

    public Date getNextOrderCutoff() {
        return this.nextOrderCutoff;
    }

    public void setNextOrderCutoff(Date nextOrderCutoff) {
        this.nextOrderCutoff = nextOrderCutoff;
        setDirty(true);
    }

    public Date getNextOrderCutoffTime() {
        return this.nextOrderCutoffTime;
    }

    public void setNextOrderCutoffTime(Date nextOrderCutoffTime) {
        this.nextOrderCutoffTime = nextOrderCutoffTime;
        setDirty(true);
    }

    public List<PhysicalInventoryPeriod> getPhysicalInventoryPeriods() {
        return this.physicalInventoryPeriods;
    }

    public void setPhysicalInventoryPeriods(List<PhysicalInventoryPeriod> physicalInventoryPeriods) {
        this.physicalInventoryPeriods = physicalInventoryPeriods;
        setDirty(true);
    }

    public String getInventoryCartAccessInterva() {
        return this.inventoryCartAccessInterva;
    }

    public void setInventoryCartAccessInterva(String inventoryCartAccessInterva) {
        this.inventoryCartAccessInterva = inventoryCartAccessInterva;
        setDirty(true);
    }




}


