package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.PropertyData;
/**
 * SiteIdentPropertiesView generated by hbm2java
*/
public class SiteIdentPropertiesView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String SITE_ID = "siteId";
    public static final String ALLOW_CORPORATE_SCHEDULED_ORDER = "allowCorporateScheduledOrder";
    public static final String BY_PASS_ORDER_ROUTING = "byPassOrderRouting";
    public static final String CONSOLIDATED_ORDER_WAREHOUSE = "consolidatedOrderWarehouse";
    public static final String DISTR_SITE_REF_NUMBER = "distrSiteRefNumber";
    public static final String ENABLE_INVENTORY = "enableInventory";
    public static final String INVENTORY_SHOPPING_TYPE = "inventoryShoppingType";
    public static final String SHARE_BUYER_ORDER_GUIDES = "shareBuyerOrderGuides";
    public static final String SHOW_REBILL_ORDER = "showRebillOrder";
    public static final String SITE_REFERENCE_NUMBER = "siteReferenceNumber";
    public static final String TAXABLE = "taxable";
    public static final String TARGET_FICILITY_RANK = "targetFicilityRank";
    public static final String PRODUCT_BUNDLE = "productBundle";
    public static final String LOCATION_LINE_LEVEL_CODE = "locationLineLevelCode";
    public static final String LOCATION_COMMENTS = "locationComments";
    public static final String LOCATION_SHIP_MSG = "locationShipMsg";

    private Long siteId;
    private PropertyData allowCorporateScheduledOrder;
    private PropertyData byPassOrderRouting;
    private PropertyData consolidatedOrderWarehouse;
    private PropertyData distrSiteRefNumber;
    private PropertyData enableInventory;
    private PropertyData inventoryShoppingType;
    private PropertyData shareBuyerOrderGuides;
    private PropertyData showRebillOrder;
    private PropertyData siteReferenceNumber;
    private PropertyData taxable;
    private PropertyData targetFicilityRank;
    private PropertyData productBundle;
    private PropertyData locationLineLevelCode;
    private PropertyData locationComments;
    private PropertyData locationShipMsg;

    public SiteIdentPropertiesView() {
    }
	
    public SiteIdentPropertiesView(Long siteId) {
        this.setSiteId(siteId);
    }

    public SiteIdentPropertiesView(Long siteId, PropertyData allowCorporateScheduledOrder, PropertyData byPassOrderRouting, PropertyData consolidatedOrderWarehouse, PropertyData distrSiteRefNumber, PropertyData enableInventory, PropertyData inventoryShoppingType, PropertyData shareBuyerOrderGuides, PropertyData showRebillOrder, PropertyData siteReferenceNumber, PropertyData taxable, PropertyData targetFicilityRank, PropertyData productBundle, PropertyData locationLineLevelCode, PropertyData locationComments, PropertyData locationShipMsg) {
        this.setSiteId(siteId);
        this.setAllowCorporateScheduledOrder(allowCorporateScheduledOrder);
        this.setByPassOrderRouting(byPassOrderRouting);
        this.setConsolidatedOrderWarehouse(consolidatedOrderWarehouse);
        this.setDistrSiteRefNumber(distrSiteRefNumber);
        this.setEnableInventory(enableInventory);
        this.setInventoryShoppingType(inventoryShoppingType);
        this.setShareBuyerOrderGuides(shareBuyerOrderGuides);
        this.setShowRebillOrder(showRebillOrder);
        this.setSiteReferenceNumber(siteReferenceNumber);
        this.setTaxable(taxable);
        this.setTargetFicilityRank(targetFicilityRank);
        this.setProductBundle(productBundle);
        this.setLocationLineLevelCode(locationLineLevelCode);
        this.setLocationComments(locationComments);
        this.setLocationShipMsg(locationShipMsg);
    }

    public Long getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
        setDirty(true);
    }

    public PropertyData getAllowCorporateScheduledOrder() {
        return this.allowCorporateScheduledOrder;
    }

    public void setAllowCorporateScheduledOrder(PropertyData allowCorporateScheduledOrder) {
        this.allowCorporateScheduledOrder = allowCorporateScheduledOrder;
        setDirty(true);
    }

    public PropertyData getByPassOrderRouting() {
        return this.byPassOrderRouting;
    }

    public void setByPassOrderRouting(PropertyData byPassOrderRouting) {
        this.byPassOrderRouting = byPassOrderRouting;
        setDirty(true);
    }

    public PropertyData getConsolidatedOrderWarehouse() {
        return this.consolidatedOrderWarehouse;
    }

    public void setConsolidatedOrderWarehouse(PropertyData consolidatedOrderWarehouse) {
        this.consolidatedOrderWarehouse = consolidatedOrderWarehouse;
        setDirty(true);
    }

    public PropertyData getDistrSiteRefNumber() {
        return this.distrSiteRefNumber;
    }

    public void setDistrSiteRefNumber(PropertyData distrSiteRefNumber) {
        this.distrSiteRefNumber = distrSiteRefNumber;
        setDirty(true);
    }

    public PropertyData getEnableInventory() {
        return this.enableInventory;
    }

    public void setEnableInventory(PropertyData enableInventory) {
        this.enableInventory = enableInventory;
        setDirty(true);
    }

    public PropertyData getInventoryShoppingType() {
        return this.inventoryShoppingType;
    }

    public void setInventoryShoppingType(PropertyData inventoryShoppingType) {
        this.inventoryShoppingType = inventoryShoppingType;
        setDirty(true);
    }

    public PropertyData getShareBuyerOrderGuides() {
        return this.shareBuyerOrderGuides;
    }

    public void setShareBuyerOrderGuides(PropertyData shareBuyerOrderGuides) {
        this.shareBuyerOrderGuides = shareBuyerOrderGuides;
        setDirty(true);
    }

    public PropertyData getShowRebillOrder() {
        return this.showRebillOrder;
    }

    public void setShowRebillOrder(PropertyData showRebillOrder) {
        this.showRebillOrder = showRebillOrder;
        setDirty(true);
    }

    public PropertyData getSiteReferenceNumber() {
        return this.siteReferenceNumber;
    }

    public void setSiteReferenceNumber(PropertyData siteReferenceNumber) {
        this.siteReferenceNumber = siteReferenceNumber;
        setDirty(true);
    }

    public PropertyData getTaxable() {
        return this.taxable;
    }

    public void setTaxable(PropertyData taxable) {
        this.taxable = taxable;
        setDirty(true);
    }

    public PropertyData getTargetFicilityRank() {
        return this.targetFicilityRank;
    }

    public void setTargetFicilityRank(PropertyData targetFicilityRank) {
        this.targetFicilityRank = targetFicilityRank;
        setDirty(true);
    }

    public PropertyData getProductBundle() {
        return this.productBundle;
    }

    public void setProductBundle(PropertyData productBundle) {
        this.productBundle = productBundle;
        setDirty(true);
    }

    public PropertyData getLocationLineLevelCode() {
        return this.locationLineLevelCode;
    }

    public void setLocationLineLevelCode(PropertyData locationLineLevelCode) {
        this.locationLineLevelCode = locationLineLevelCode;
        setDirty(true);
    }

    public PropertyData getLocationComments() {
        return this.locationComments;
    }

    public void setLocationComments(PropertyData locationComments) {
        this.locationComments = locationComments;
        setDirty(true);
    }

    public PropertyData getLocationShipMsg() {
        return this.locationShipMsg;
    }

    public void setLocationShipMsg(PropertyData locationShipMsg) {
        this.locationShipMsg = locationShipMsg;
        setDirty(true);
    }




}


