package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.FiscalCalenderData;
import com.espendwise.manta.model.data.FiscalCalenderDetailData;
import java.util.List;
/**
 * SiteBudgetYearView generated by hbm2java
*/
public class SiteBudgetYearView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String FISCAL_CALENDAR = "fiscalCalendar";
    public static final String ACCOUNT_ID = "accountId";
    public static final String SITE_ID = "siteId";
    public static final String COST_CENTER_BUDGETS = "costCenterBudgets";

    private FiscalCalendarPhysicalView fiscalCalendar;
    private Long accountId;
    private Long siteId;
    private List<CostCenterBudgetView> costCenterBudgets;

    public SiteBudgetYearView() {
    }
	
    public SiteBudgetYearView(FiscalCalendarPhysicalView fiscalCalendar) {
        this.setFiscalCalendar(fiscalCalendar);
    }

    public SiteBudgetYearView(FiscalCalendarPhysicalView fiscalCalendar, Long accountId, Long siteId, List<CostCenterBudgetView> costCenterBudgets) {
        this.setFiscalCalendar(fiscalCalendar);
        this.setAccountId(accountId);
        this.setSiteId(siteId);
        this.setCostCenterBudgets(costCenterBudgets);
    }

    public FiscalCalendarPhysicalView getFiscalCalendar() {
        return this.fiscalCalendar;
    }

    public void setFiscalCalendar(FiscalCalendarPhysicalView fiscalCalendar) {
        this.fiscalCalendar = fiscalCalendar;
        setDirty(true);
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
        setDirty(true);
    }

    public Long getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
        setDirty(true);
    }

    public List<CostCenterBudgetView> getCostCenterBudgets() {
        return this.costCenterBudgets;
    }

    public void setCostCenterBudgets(List<CostCenterBudgetView> costCenterBudgets) {
        this.costCenterBudgets = costCenterBudgets;
        setDirty(true);
    }




}


