package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * SiteListView generated by hbm2java
*/
public class SiteListView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String SITE_ID = "siteId";
    public static final String SITE_NAME = "siteName";
    public static final String ACCOUNT_ID = "accountId";
    public static final String ACCOUNT_NAME = "accountName";
    public static final String STATUS = "status";
    public static final String ADDRESS1 = "address1";
    public static final String ADDRESS2 = "address2";
    public static final String ADDRESS3 = "address3";
    public static final String ADDRESS4 = "address4";
    public static final String COUNTRY_CD = "countryCd";
    public static final String COUNTY_CD = "countyCd";
    public static final String CITY = "city";
    public static final String STATE = "state";
    public static final String POSTAL_CODE = "postalCode";

    private Long siteId;
    private String siteName;
    private Long accountId;
    private String accountName;
    private String status;
    private String address1;
    private String address2;
    private String address3;
    private String address4;
    private String countryCd;
    private String countyCd;
    private String city;
    private String state;
    private String postalCode;

    public SiteListView() {
    }
	
    public SiteListView(Long siteId) {
        this.setSiteId(siteId);
    }

    public SiteListView(Long siteId, String siteName, Long accountId, String accountName, String status, String address1, String address2, String address3, String address4, String countryCd, String countyCd, String city, String state, String postalCode) {
        this.setSiteId(siteId);
        this.setSiteName(siteName);
        this.setAccountId(accountId);
        this.setAccountName(accountName);
        this.setStatus(status);
        this.setAddress1(address1);
        this.setAddress2(address2);
        this.setAddress3(address3);
        this.setAddress4(address4);
        this.setCountryCd(countryCd);
        this.setCountyCd(countyCd);
        this.setCity(city);
        this.setState(state);
        this.setPostalCode(postalCode);
    }

    public Long getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
        setDirty(true);
    }

    public String getSiteName() {
        return this.siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
        setDirty(true);
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
        setDirty(true);
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
        setDirty(true);
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
        setDirty(true);
    }

    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
        setDirty(true);
    }

    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
        setDirty(true);
    }

    public String getAddress3() {
        return this.address3;
    }

    public void setAddress3(String address3) {
        this.address3 = address3;
        setDirty(true);
    }

    public String getAddress4() {
        return this.address4;
    }

    public void setAddress4(String address4) {
        this.address4 = address4;
        setDirty(true);
    }

    public String getCountryCd() {
        return this.countryCd;
    }

    public void setCountryCd(String countryCd) {
        this.countryCd = countryCd;
        setDirty(true);
    }

    public String getCountyCd() {
        return this.countyCd;
    }

    public void setCountyCd(String countyCd) {
        this.countyCd = countyCd;
        setDirty(true);
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
        setDirty(true);
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
        setDirty(true);
    }

    public String getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
        setDirty(true);
    }




}


