package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.BusEntityData;
import com.espendwise.manta.model.data.PropertyData;
import java.util.List;
/**
 * SiteIdentView generated by hbm2java
*/
public class SiteIdentView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUS_ENTITY_DATA = "busEntityData";
    public static final String ACCOUNT_ID = "accountId";
    public static final String ACCOUNT_NAME = "accountName";
    public static final String CONTACT = "contact";
    public static final String PROPERTIES = "properties";
    public static final String CORPORATE_SCHEDULE_CORPORATE = "corporateScheduleCorporate";

    private BusEntityData busEntityData;
    private Long accountId;
    private String accountName;
    private ContactView contact;
    private List<PropertyData> properties;
    private CorporateScheduleView corporateScheduleCorporate;

    public SiteIdentView() {
    }
	
    public SiteIdentView(BusEntityData busEntityData) {
        this.setBusEntityData(busEntityData);
    }

    public SiteIdentView(BusEntityData busEntityData, Long accountId, String accountName, ContactView contact, List<PropertyData> properties, CorporateScheduleView corporateScheduleCorporate) {
        this.setBusEntityData(busEntityData);
        this.setAccountId(accountId);
        this.setAccountName(accountName);
        this.setContact(contact);
        this.setProperties(properties);
        this.setCorporateScheduleCorporate(corporateScheduleCorporate);
    }

    public BusEntityData getBusEntityData() {
        return this.busEntityData;
    }

    public void setBusEntityData(BusEntityData busEntityData) {
        this.busEntityData = busEntityData;
        setDirty(true);
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
        setDirty(true);
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
        setDirty(true);
    }

    public ContactView getContact() {
        return this.contact;
    }

    public void setContact(ContactView contact) {
        this.contact = contact;
        setDirty(true);
    }

    public List<PropertyData> getProperties() {
        return this.properties;
    }

    public void setProperties(List<PropertyData> properties) {
        this.properties = properties;
        setDirty(true);
    }

    public CorporateScheduleView getCorporateScheduleCorporate() {
        return this.corporateScheduleCorporate;
    }

    public void setCorporateScheduleCorporate(CorporateScheduleView corporateScheduleCorporate) {
        this.corporateScheduleCorporate = corporateScheduleCorporate;
        setDirty(true);
    }




}


