package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * SiteHeaderView generated by hbm2java
*/
public class SiteHeaderView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String SITE_ID = "siteId";
    public static final String SITE_NAME = "siteName";
    public static final String ACCOUNT_ID = "accountId";
    public static final String ACCOUNT_NAME = "accountName";

    private Long siteId;
    private String siteName;
    private Long accountId;
    private String accountName;

    public SiteHeaderView() {
    }
	
    public SiteHeaderView(Long siteId) {
        this.setSiteId(siteId);
    }

    public SiteHeaderView(Long siteId, String siteName, Long accountId, String accountName) {
        this.setSiteId(siteId);
        this.setSiteName(siteName);
        this.setAccountId(accountId);
        this.setAccountName(accountName);
    }

    public Long getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
        setDirty(true);
    }

    public String getSiteName() {
        return this.siteName;
    }

    public void setSiteName(String siteName) {
        this.siteName = siteName;
        setDirty(true);
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public void setAccountId(Long accountId) {
        this.accountId = accountId;
        setDirty(true);
    }

    public String getAccountName() {
        return this.accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
        setDirty(true);
    }




}


