package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
/**
 * StoreMsgAccountConfigView generated by hbm2java
*/
public class StoreMsgAccountConfigView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUS_ENTITY_ID_ID = "busEntityIdId";
    public static final String STATUS_CD = "statusCd";
    public static final String SHORT_DESC = "shortDesc";

    private Long busEntityIdId;
    private Long statusCd;
    private String shortDesc;

    public StoreMsgAccountConfigView() {
    }
	
    public StoreMsgAccountConfigView(Long busEntityIdId) {
        this.setBusEntityIdId(busEntityIdId);
    }

    public StoreMsgAccountConfigView(Long busEntityIdId, Long statusCd, String shortDesc) {
        this.setBusEntityIdId(busEntityIdId);
        this.setStatusCd(statusCd);
        this.setShortDesc(shortDesc);
    }

    public Long getBusEntityIdId() {
        return this.busEntityIdId;
    }

    public void setBusEntityIdId(Long busEntityIdId) {
        this.busEntityIdId = busEntityIdId;
        setDirty(true);
    }

    public Long getStatusCd() {
        return this.statusCd;
    }

    public void setStatusCd(Long statusCd) {
        this.statusCd = statusCd;
        setDirty(true);
    }

    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }




}


