package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.util.HomeViewType;
/**
 * StoreUiOptionView generated by hbm2java
*/
public class StoreUiOptionView extends UiOptionView implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String STORE_ID = "storeId";
    public static final String LOGO_BINARY_DATA = "logoBinaryData";
    public static final String HOME_VIEW_TYPE = "homeViewType";

    private Long storeId;
    private byte[] logoBinaryData;
    private HomeViewType homeViewType;

    public StoreUiOptionView() {
    }
	
    public StoreUiOptionView(Long storeId) {
        this.setStoreId(storeId);
    }

    public StoreUiOptionView(Long storeId, byte[] logoBinaryData, HomeViewType homeViewType) {
        this.setStoreId(storeId);
        this.setLogoBinaryData(logoBinaryData);
        this.setHomeViewType(homeViewType);
    }

    public Long getStoreId() {
        return this.storeId;
    }

    public void setStoreId(Long storeId) {
        this.storeId = storeId;
        setDirty(true);
    }

    public byte[] getLogoBinaryData() {
        return this.logoBinaryData;
    }

    public void setLogoBinaryData(byte[] logoBinaryData) {
        this.logoBinaryData = logoBinaryData;
        setDirty(true);
    }

    public HomeViewType getHomeViewType() {
        return this.homeViewType;
    }

    public void setHomeViewType(HomeViewType homeViewType) {
        this.homeViewType = homeViewType;
        setDirty(true);
    }




}


