package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.GenericReportData;
import com.espendwise.manta.model.data.GroupData;
import java.util.List;
/**
 * UserGroupInformationView generated by hbm2java
*/
public class UserGroupInformationView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String GROUP = "group";
    public static final String APPLICATION_FUNCTION_NAMES = "applicationFunctionNames";
    public static final String REPORTS = "reports";

    private GroupData group;
    private List<String> applicationFunctionNames;
    private List<GenericReportData> reports;

    public UserGroupInformationView() {
    }
	
    public UserGroupInformationView(GroupData group) {
        this.setGroup(group);
    }

    public UserGroupInformationView(GroupData group, List<String> applicationFunctionNames, List<GenericReportData> reports) {
        this.setGroup(group);
        this.setApplicationFunctionNames(applicationFunctionNames);
        this.setReports(reports);
    }

    public GroupData getGroup() {
        return this.group;
    }

    public void setGroup(GroupData group) {
        this.group = group;
        setDirty(true);
    }

    public List<String> getApplicationFunctionNames() {
        return this.applicationFunctionNames;
    }

    public void setApplicationFunctionNames(List<String> applicationFunctionNames) {
        this.applicationFunctionNames = applicationFunctionNames;
        setDirty(true);
    }

    public List<GenericReportData> getReports() {
        return this.reports;
    }

    public void setReports(List<GenericReportData> reports) {
        this.reports = reports;
        setDirty(true);
    }




}


