package com.espendwise.manta.model.view;
// Generated by Hibernate Tools


import com.espendwise.manta.model.ValueObject;
import com.espendwise.manta.model.data.AddressData;
import com.espendwise.manta.model.data.EmailData;
import com.espendwise.manta.model.data.PhoneData;
import com.espendwise.manta.model.data.PropertyData;
import com.espendwise.manta.model.data.UserAssocData;
import com.espendwise.manta.model.data.UserData;
import java.util.List;
/**
 * UserIdentView generated by hbm2java
*/
public class UserIdentView extends ValueObject implements java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String USER_DATA = "userData";
    public static final String EMAIL_DATA = "emailData";
    public static final String ADDRESS_DATA = "addressData";
    public static final String PHONE_DATA = "phoneData";
    public static final String FAX_PHONE_DATA = "faxPhoneData";
    public static final String MOBILE_PHONE_DATA = "mobilePhoneData";
    public static final String ESCALATION_EMAIL_DATA = "escalationEmailData";
    public static final String SMS_EMAIL_DATA = "smsEmailData";
    public static final String USER_ASSOCS = "userAssocs";
    public static final String USER_PROPERTIES = "userProperties";
    public static final String USER_STORE_ASSOCS = "userStoreAssocs";

    private UserData userData;
    private EmailData emailData;
    private AddressData addressData;
    private PhoneData phoneData;
    private PhoneData faxPhoneData;
    private PhoneData mobilePhoneData;
    private EmailData escalationEmailData;
    private EmailData smsEmailData;
    private List<UserAssocData> userAssocs;
    private List<PropertyData> userProperties;
    private List<AllStoreIdentificationView> userStoreAssocs;

    public UserIdentView() {
    }
	
    public UserIdentView(UserData userData) {
        this.setUserData(userData);
    }

    public UserIdentView(UserData userData, EmailData emailData, AddressData addressData, PhoneData phoneData, PhoneData faxPhoneData, PhoneData mobilePhoneData, EmailData escalationEmailData, EmailData smsEmailData, List<UserAssocData> userAssocs, List<PropertyData> userProperties, List<AllStoreIdentificationView> userStoreAssocs) {
        this.setUserData(userData);
        this.setEmailData(emailData);
        this.setAddressData(addressData);
        this.setPhoneData(phoneData);
        this.setFaxPhoneData(faxPhoneData);
        this.setMobilePhoneData(mobilePhoneData);
        this.setEscalationEmailData(escalationEmailData);
        this.setSmsEmailData(smsEmailData);
        this.setUserAssocs(userAssocs);
        this.setUserProperties(userProperties);
        this.setUserStoreAssocs(userStoreAssocs);
    }

    public UserData getUserData() {
        return this.userData;
    }

    public void setUserData(UserData userData) {
        this.userData = userData;
        setDirty(true);
    }

    public EmailData getEmailData() {
        return this.emailData;
    }

    public void setEmailData(EmailData emailData) {
        this.emailData = emailData;
        setDirty(true);
    }

    public AddressData getAddressData() {
        return this.addressData;
    }

    public void setAddressData(AddressData addressData) {
        this.addressData = addressData;
        setDirty(true);
    }

    public PhoneData getPhoneData() {
        return this.phoneData;
    }

    public void setPhoneData(PhoneData phoneData) {
        this.phoneData = phoneData;
        setDirty(true);
    }

    public PhoneData getFaxPhoneData() {
        return this.faxPhoneData;
    }

    public void setFaxPhoneData(PhoneData faxPhoneData) {
        this.faxPhoneData = faxPhoneData;
        setDirty(true);
    }

    public PhoneData getMobilePhoneData() {
        return this.mobilePhoneData;
    }

    public void setMobilePhoneData(PhoneData mobilePhoneData) {
        this.mobilePhoneData = mobilePhoneData;
        setDirty(true);
    }

    public EmailData getEscalationEmailData() {
        return this.escalationEmailData;
    }

    public void setEscalationEmailData(EmailData escalationEmailData) {
        this.escalationEmailData = escalationEmailData;
        setDirty(true);
    }

    public EmailData getSmsEmailData() {
        return this.smsEmailData;
    }

    public void setSmsEmailData(EmailData smsEmailData) {
        this.smsEmailData = smsEmailData;
        setDirty(true);
    }

    public List<UserAssocData> getUserAssocs() {
        return this.userAssocs;
    }

    public void setUserAssocs(List<UserAssocData> userAssocs) {
        this.userAssocs = userAssocs;
        setDirty(true);
    }

    public List<PropertyData> getUserProperties() {
        return this.userProperties;
    }

    public void setUserProperties(List<PropertyData> userProperties) {
        this.userProperties = userProperties;
        setDirty(true);
    }

    public List<AllStoreIdentificationView> getUserStoreAssocs() {
        return this.userStoreAssocs;
    }

    public void setUserStoreAssocs(List<AllStoreIdentificationView> userStoreAssocs) {
        this.userStoreAssocs = userStoreAssocs;
        setDirty(true);
    }




}


