${pojo.getPackageDeclaration()}
// Generated by Hibernate Tools

<#assign classbody>
<#include "PojoTypeDeclaration.ftl"/> {

<#if !pojo.isInterface()>
<#include "PojoSerialVersionUID.ftl"/>
<#if pojo.extendsFields>
<#include "PojoFields.ftl"/>
<#include "PojoConstructors.ftl"/>
<#include "PojoPropertyAccessors.ftl"/>

<#--<#include "PojoTableObjImplSupport.ftl"/>-->
</#if>
<#include "PojoToString.ftl"/>

<#include "pojo/PojoEqualsHashcode.ftl"/>

<#else>
<#include "pojo/PojoInterfacePropertyAccessors.ftl"/>

</#if>
<#include "pojo/PojoExtraClassCode.ftl"/>

}
</#assign>

${pojo.generateImports()}
${classbody}

