//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 11:35:30 AM MSK 
//


package com.espendwise.tools.gencode.dbxml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for table complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="table">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="column" type="{}column" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="primaryKey" type="{}primaryKey"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serialVersionDataUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serialVersionVectorUID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="cache" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "table", propOrder = {
    "column",
    "primaryKey"
})
public class Table {

    protected List<Column> column;
    @XmlElement(required = true)
    protected PrimaryKey primaryKey;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String serialVersionDataUID;
    @XmlAttribute
    protected String serialVersionVectorUID;
    @XmlAttribute
    protected String cache;

    /**
     * Gets the value of the column property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the column property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Column }
     * 
     * 
     */
    public List<Column> getColumn() {
        if (column == null) {
            column = new ArrayList<Column>();
        }
        return this.column;
    }

    /**
     * Gets the value of the primaryKey property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryKey }
     *     
     */
    public PrimaryKey getPrimaryKey() {
        return primaryKey;
    }

    /**
     * Sets the value of the primaryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryKey }
     *     
     */
    public void setPrimaryKey(PrimaryKey value) {
        this.primaryKey = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the serialVersionDataUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialVersionDataUID() {
        return serialVersionDataUID;
    }

    /**
     * Sets the value of the serialVersionDataUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialVersionDataUID(String value) {
        this.serialVersionDataUID = value;
    }

    /**
     * Gets the value of the serialVersionVectorUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialVersionVectorUID() {
        return serialVersionVectorUID;
    }

    /**
     * Sets the value of the serialVersionVectorUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialVersionVectorUID(String value) {
        this.serialVersionVectorUID = value;
    }

    /**
     * Gets the value of the cache property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCache() {
        return cache;
    }

    /**
     * Sets the value of the cache property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCache(String value) {
        this.cache = value;
    }

}
