package com.espendwise.manta.service;

//Generated by DataAccessJavaClassGenerator.java
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

public abstract class DatabaseAccess {

    private static final String PERSISTENCE_UNIT_DSMAIN = "dsmain";
    private static final String PERSISTENCE_UNIT_DS01 = "ds01";
    private static final String PERSISTENCE_UNIT_DS02 = "ds02";

    private static final String[] AVAILABLE_UNITS =  new String[] {
        PERSISTENCE_UNIT_DS01,
        PERSISTENCE_UNIT_DS02
    };


    @PersistenceContext(unitName = PERSISTENCE_UNIT_DSMAIN)
    private transient EntityManager entityManagerDsmain;

    @PersistenceContext(unitName = PERSISTENCE_UNIT_DS01)
    private transient EntityManager entityManagerDs01;

    @PersistenceContext(unitName = PERSISTENCE_UNIT_DS02)
    private transient EntityManager entityManagerDs02;


    public EntityManager getEntityManager(String unit) {
        if(PERSISTENCE_UNIT_DSMAIN.equals(unit)) {
            return entityManagerDsmain;
        } else if(PERSISTENCE_UNIT_DS01.equals(unit)) {
            return entityManagerDs01;
        } else if(PERSISTENCE_UNIT_DS02.equals(unit)) {
            return entityManagerDs02;
        }

        return null;

    }

    public static String getMainUnit() {
        return PERSISTENCE_UNIT_DSMAIN;
    }

    public static String[] availableUnits() {
        return AVAILABLE_UNITS;
    }

}
