package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * BudgetData generated by hbm2java
*/
@Entity
@Table(name="CLW_BUDGET")
public class BudgetData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUDGET_ID = "budgetId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String COST_CENTER_ID = "costCenterId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String BUDGET_STATUS_CD = "budgetStatusCd";
    public static final String BUDGET_TYPE_CD = "budgetTypeCd";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String BUDGET_THRESHOLD = "budgetThreshold";
    public static final String BUDGET_YEAR = "budgetYear";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String AMOUNT1 = "amount1";
    public static final String AMOUNT2 = "amount2";
    public static final String AMOUNT3 = "amount3";
    public static final String AMOUNT4 = "amount4";
    public static final String AMOUNT5 = "amount5";
    public static final String AMOUNT6 = "amount6";
    public static final String AMOUNT7 = "amount7";
    public static final String AMOUNT8 = "amount8";
    public static final String AMOUNT9 = "amount9";
    public static final String AMOUNT10 = "amount10";
    public static final String AMOUNT11 = "amount11";
    public static final String AMOUNT12 = "amount12";
    public static final String AMOUNT13 = "amount13";

    private Long budgetId;
    private Long busEntityId;
    private Long costCenterId;
    private String shortDesc;
    private String budgetStatusCd;
    private String budgetTypeCd;
    private Date effDate;
    private Date expDate;
    private String budgetThreshold;
    private int budgetYear;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private BigDecimal amount1;
    private BigDecimal amount2;
    private BigDecimal amount3;
    private BigDecimal amount4;
    private BigDecimal amount5;
    private BigDecimal amount6;
    private BigDecimal amount7;
    private BigDecimal amount8;
    private BigDecimal amount9;
    private BigDecimal amount10;
    private BigDecimal amount11;
    private BigDecimal amount12;
    private BigDecimal amount13;

    public BudgetData() {
    }
	
    public BudgetData(Long busEntityId, Long costCenterId, String budgetStatusCd, String budgetTypeCd, int budgetYear, Date addDate, Date modDate) {
        this.setBusEntityId(busEntityId);
        this.setCostCenterId(costCenterId);
        this.setBudgetStatusCd(budgetStatusCd);
        this.setBudgetTypeCd(budgetTypeCd);
        this.setBudgetYear(budgetYear);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public BudgetData(Long busEntityId, Long costCenterId, String shortDesc, String budgetStatusCd, String budgetTypeCd, Date effDate, Date expDate, String budgetThreshold, int budgetYear, Date addDate, String addBy, Date modDate, String modBy, BigDecimal amount1, BigDecimal amount2, BigDecimal amount3, BigDecimal amount4, BigDecimal amount5, BigDecimal amount6, BigDecimal amount7, BigDecimal amount8, BigDecimal amount9, BigDecimal amount10, BigDecimal amount11, BigDecimal amount12, BigDecimal amount13) {
        this.setBusEntityId(busEntityId);
        this.setCostCenterId(costCenterId);
        this.setShortDesc(shortDesc);
        this.setBudgetStatusCd(budgetStatusCd);
        this.setBudgetTypeCd(budgetTypeCd);
        this.setEffDate(effDate);
        this.setExpDate(expDate);
        this.setBudgetThreshold(budgetThreshold);
        this.setBudgetYear(budgetYear);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setAmount1(amount1);
        this.setAmount2(amount2);
        this.setAmount3(amount3);
        this.setAmount4(amount4);
        this.setAmount5(amount5);
        this.setAmount6(amount6);
        this.setAmount7(amount7);
        this.setAmount8(amount8);
        this.setAmount9(amount9);
        this.setAmount10(amount10);
        this.setAmount11(amount11);
        this.setAmount12(amount12);
        this.setAmount13(amount13);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_BUDGET_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="BUDGET_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBudgetId() {
        return this.budgetId;
    }

    public void setBudgetId(Long budgetId) {
        this.budgetId = budgetId;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    
    @Column(name="COST_CENTER_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getCostCenterId() {
        return this.costCenterId;
    }

    public void setCostCenterId(Long costCenterId) {
        this.costCenterId = costCenterId;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC")
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="BUDGET_STATUS_CD", nullable=false, length=30)
    public String getBudgetStatusCd() {
        return this.budgetStatusCd;
    }

    public void setBudgetStatusCd(String budgetStatusCd) {
        this.budgetStatusCd = budgetStatusCd;
        setDirty(true);
    }

    
    @Column(name="BUDGET_TYPE_CD", nullable=false, length=30)
    public String getBudgetTypeCd() {
        return this.budgetTypeCd;
    }

    public void setBudgetTypeCd(String budgetTypeCd) {
        this.budgetTypeCd = budgetTypeCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFF_DATE", length=7)
    public Date getEffDate() {
        return this.effDate;
    }

    public void setEffDate(Date effDate) {
        this.effDate = effDate;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXP_DATE", length=7)
    public Date getExpDate() {
        return this.expDate;
    }

    public void setExpDate(Date expDate) {
        this.expDate = expDate;
        setDirty(true);
    }

    
    @Column(name="BUDGET_THRESHOLD", length=10)
    public String getBudgetThreshold() {
        return this.budgetThreshold;
    }

    public void setBudgetThreshold(String budgetThreshold) {
        this.budgetThreshold = budgetThreshold;
        setDirty(true);
    }

    
    @Column(name="BUDGET_YEAR", nullable=false, columnDefinition="number", precision=5, scale=0)
    public int getBudgetYear() {
        return this.budgetYear;
    }

    public void setBudgetYear(int budgetYear) {
        this.budgetYear = budgetYear;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="AMOUNT1", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount1() {
        return this.amount1;
    }

    public void setAmount1(BigDecimal amount1) {
        this.amount1 = amount1;
        setDirty(true);
    }

    
    @Column(name="AMOUNT2", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount2() {
        return this.amount2;
    }

    public void setAmount2(BigDecimal amount2) {
        this.amount2 = amount2;
        setDirty(true);
    }

    
    @Column(name="AMOUNT3", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount3() {
        return this.amount3;
    }

    public void setAmount3(BigDecimal amount3) {
        this.amount3 = amount3;
        setDirty(true);
    }

    
    @Column(name="AMOUNT4", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount4() {
        return this.amount4;
    }

    public void setAmount4(BigDecimal amount4) {
        this.amount4 = amount4;
        setDirty(true);
    }

    
    @Column(name="AMOUNT5", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount5() {
        return this.amount5;
    }

    public void setAmount5(BigDecimal amount5) {
        this.amount5 = amount5;
        setDirty(true);
    }

    
    @Column(name="AMOUNT6", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount6() {
        return this.amount6;
    }

    public void setAmount6(BigDecimal amount6) {
        this.amount6 = amount6;
        setDirty(true);
    }

    
    @Column(name="AMOUNT7", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount7() {
        return this.amount7;
    }

    public void setAmount7(BigDecimal amount7) {
        this.amount7 = amount7;
        setDirty(true);
    }

    
    @Column(name="AMOUNT8", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount8() {
        return this.amount8;
    }

    public void setAmount8(BigDecimal amount8) {
        this.amount8 = amount8;
        setDirty(true);
    }

    
    @Column(name="AMOUNT9", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount9() {
        return this.amount9;
    }

    public void setAmount9(BigDecimal amount9) {
        this.amount9 = amount9;
        setDirty(true);
    }

    
    @Column(name="AMOUNT10", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount10() {
        return this.amount10;
    }

    public void setAmount10(BigDecimal amount10) {
        this.amount10 = amount10;
        setDirty(true);
    }

    
    @Column(name="AMOUNT11", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount11() {
        return this.amount11;
    }

    public void setAmount11(BigDecimal amount11) {
        this.amount11 = amount11;
        setDirty(true);
    }

    
    @Column(name="AMOUNT12", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount12() {
        return this.amount12;
    }

    public void setAmount12(BigDecimal amount12) {
        this.amount12 = amount12;
        setDirty(true);
    }

    
    @Column(name="AMOUNT13", columnDefinition="number", precision=15, scale=3)
    public BigDecimal getAmount13() {
        return this.amount13;
    }

    public void setAmount13(BigDecimal amount13) {
        this.amount13 = amount13;
        setDirty(true);
    }




}


