package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * BudgetDetailData generated by hbm2java
*/
@Entity
@Table(name="CLW_BUDGET_DETAIL")
public class BudgetDetailData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUDGET_DETAIL_ID = "budgetDetailId";
    public static final String BUDGET_ID = "budgetId";
    public static final String PERIOD = "period";
    public static final String AMOUNT = "amount";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    private Long budgetDetailId;
    private Long budgetId;
    private int period;
    private BigDecimal amount;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;

    public BudgetDetailData() {
    }
	
    public BudgetDetailData(Long budgetId, int period, Date addDate, Date modDate) {
        this.setBudgetId(budgetId);
        this.setPeriod(period);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public BudgetDetailData(Long budgetId, int period, BigDecimal amount, Date addDate, String addBy, Date modDate, String modBy) {
        this.setBudgetId(budgetId);
        this.setPeriod(period);
        this.setAmount(amount);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_BUDGET_DETAIL_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="BUDGET_DETAIL_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBudgetDetailId() {
        return this.budgetDetailId;
    }

    public void setBudgetDetailId(Long budgetDetailId) {
        this.budgetDetailId = budgetDetailId;
        setDirty(true);
    }

    
    @Column(name="BUDGET_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBudgetId() {
        return this.budgetId;
    }

    public void setBudgetId(Long budgetId) {
        this.budgetId = budgetId;
        setDirty(true);
    }

    
    @Column(name="PERIOD", nullable=false, columnDefinition="number", precision=10, scale=0)
    public int getPeriod() {
        return this.period;
    }

    public void setPeriod(int period) {
        this.period = period;
        setDirty(true);
    }

    
    @Column(name="AMOUNT", columnDefinition="number", precision=20, scale=8)
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }




}


