package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * BusEntityAssocData generated by hbm2java
*/
@Entity
@Table(name="CLW_BUS_ENTITY_ASSOC")
public class BusEntityAssocData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUS_ENTITY_ASSOC_ID = "busEntityAssocId";
    public static final String BUS_ENTITY1_ID = "busEntity1Id";
    public static final String BUS_ENTITY2_ID = "busEntity2Id";
    public static final String BUS_ENTITY_ASSOC_CD = "busEntityAssocCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    private Long busEntityAssocId;
    private Long busEntity1Id;
    private Long busEntity2Id;
    private String busEntityAssocCd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;

    public BusEntityAssocData() {
    }
	
    public BusEntityAssocData(Long busEntity1Id, Long busEntity2Id, String busEntityAssocCd, Date addDate, Date modDate) {
        this.setBusEntity1Id(busEntity1Id);
        this.setBusEntity2Id(busEntity2Id);
        this.setBusEntityAssocCd(busEntityAssocCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public BusEntityAssocData(Long busEntity1Id, Long busEntity2Id, String busEntityAssocCd, Date addDate, String addBy, Date modDate, String modBy) {
        this.setBusEntity1Id(busEntity1Id);
        this.setBusEntity2Id(busEntity2Id);
        this.setBusEntityAssocCd(busEntityAssocCd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_BUS_ENTITY_ASSOC_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="BUS_ENTITY_ASSOC_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBusEntityAssocId() {
        return this.busEntityAssocId;
    }

    public void setBusEntityAssocId(Long busEntityAssocId) {
        this.busEntityAssocId = busEntityAssocId;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY1_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBusEntity1Id() {
        return this.busEntity1Id;
    }

    public void setBusEntity1Id(Long busEntity1Id) {
        this.busEntity1Id = busEntity1Id;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY2_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBusEntity2Id() {
        return this.busEntity2Id;
    }

    public void setBusEntity2Id(Long busEntity2Id) {
        this.busEntity2Id = busEntity2Id;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_ASSOC_CD", nullable=false, length=30)
    public String getBusEntityAssocCd() {
        return this.busEntityAssocCd;
    }

    public void setBusEntityAssocCd(String busEntityAssocCd) {
        this.busEntityAssocCd = busEntityAssocCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }




}


