package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * BusEntityData generated by hbm2java
*/
@Entity
@Table(name="CLW_BUS_ENTITY")
public class BusEntityData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String LONG_DESC = "longDesc";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String BUS_ENTITY_TYPE_CD = "busEntityTypeCd";
    public static final String BUS_ENTITY_STATUS_CD = "busEntityStatusCd";
    public static final String WORKFLOW_ROLE_CD = "workflowRoleCd";
    public static final String LOCALE_CD = "localeCd";
    public static final String ERP_NUM = "erpNum";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String TIME_ZONE_CD = "timeZoneCd";

    private Long busEntityId;
    private String shortDesc;
    private String longDesc;
    private Date effDate;
    private Date expDate;
    private String busEntityTypeCd;
    private String busEntityStatusCd;
    private String workflowRoleCd;
    private String localeCd;
    private String erpNum;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private String timeZoneCd;

    public BusEntityData() {
    }
	
    public BusEntityData(String shortDesc, String busEntityTypeCd, String busEntityStatusCd, String workflowRoleCd, String localeCd, Date addDate, Date modDate) {
        this.setShortDesc(shortDesc);
        this.setBusEntityTypeCd(busEntityTypeCd);
        this.setBusEntityStatusCd(busEntityStatusCd);
        this.setWorkflowRoleCd(workflowRoleCd);
        this.setLocaleCd(localeCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public BusEntityData(String shortDesc, String longDesc, Date effDate, Date expDate, String busEntityTypeCd, String busEntityStatusCd, String workflowRoleCd, String localeCd, String erpNum, Date addDate, String addBy, Date modDate, String modBy, String timeZoneCd) {
        this.setShortDesc(shortDesc);
        this.setLongDesc(longDesc);
        this.setEffDate(effDate);
        this.setExpDate(expDate);
        this.setBusEntityTypeCd(busEntityTypeCd);
        this.setBusEntityStatusCd(busEntityStatusCd);
        this.setWorkflowRoleCd(workflowRoleCd);
        this.setLocaleCd(localeCd);
        this.setErpNum(erpNum);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setTimeZoneCd(timeZoneCd);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_BUS_ENTITY_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="BUS_ENTITY_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC", nullable=false)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="LONG_DESC")
    public String getLongDesc() {
        return this.longDesc;
    }

    public void setLongDesc(String longDesc) {
        this.longDesc = longDesc;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFF_DATE", length=7)
    public Date getEffDate() {
        return this.effDate;
    }

    public void setEffDate(Date effDate) {
        this.effDate = effDate;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXP_DATE", length=7)
    public Date getExpDate() {
        return this.expDate;
    }

    public void setExpDate(Date expDate) {
        this.expDate = expDate;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_TYPE_CD", nullable=false, length=30)
    public String getBusEntityTypeCd() {
        return this.busEntityTypeCd;
    }

    public void setBusEntityTypeCd(String busEntityTypeCd) {
        this.busEntityTypeCd = busEntityTypeCd;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_STATUS_CD", nullable=false, length=30)
    public String getBusEntityStatusCd() {
        return this.busEntityStatusCd;
    }

    public void setBusEntityStatusCd(String busEntityStatusCd) {
        this.busEntityStatusCd = busEntityStatusCd;
        setDirty(true);
    }

    
    @Column(name="WORKFLOW_ROLE_CD", nullable=false, length=30)
    public String getWorkflowRoleCd() {
        return this.workflowRoleCd;
    }

    public void setWorkflowRoleCd(String workflowRoleCd) {
        this.workflowRoleCd = workflowRoleCd;
        setDirty(true);
    }

    
    @Column(name="LOCALE_CD", nullable=false, length=30)
    public String getLocaleCd() {
        return this.localeCd;
    }

    public void setLocaleCd(String localeCd) {
        this.localeCd = localeCd;
        setDirty(true);
    }

    
    @Column(name="ERP_NUM", length=30)
    public String getErpNum() {
        return this.erpNum;
    }

    public void setErpNum(String erpNum) {
        this.erpNum = erpNum;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="TIME_ZONE_CD", length=30)
    public String getTimeZoneCd() {
        return this.timeZoneCd;
    }

    public void setTimeZoneCd(String timeZoneCd) {
        this.timeZoneCd = timeZoneCd;
        setDirty(true);
    }




}


