package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * CatalogData generated by hbm2java
*/
@Entity
@Table(name="CLW_CATALOG")
public class CatalogData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String CATALOG_ID = "catalogId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String SHIPPING_MESSAGE = "shippingMessage";
    public static final String CATALOG_STATUS_CD = "catalogStatusCd";
    public static final String CATALOG_TYPE_CD = "catalogTypeCd";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String RANK_WEIGHT = "rankWeight";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String LOADER_FIELD = "loaderField";

    private Long catalogId;
    private String shortDesc;
    private String shippingMessage;
    private String catalogStatusCd;
    private String catalogTypeCd;
    private Date effDate;
    private Date expDate;
    private Long rankWeight;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private String loaderField;

    public CatalogData() {
    }
	
    public CatalogData(String shortDesc, String catalogStatusCd, String catalogTypeCd, Date addDate, Date modDate) {
        this.setShortDesc(shortDesc);
        this.setCatalogStatusCd(catalogStatusCd);
        this.setCatalogTypeCd(catalogTypeCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public CatalogData(String shortDesc, String shippingMessage, String catalogStatusCd, String catalogTypeCd, Date effDate, Date expDate, Long rankWeight, Date addDate, String addBy, Date modDate, String modBy, String loaderField) {
        this.setShortDesc(shortDesc);
        this.setShippingMessage(shippingMessage);
        this.setCatalogStatusCd(catalogStatusCd);
        this.setCatalogTypeCd(catalogTypeCd);
        this.setEffDate(effDate);
        this.setExpDate(expDate);
        this.setRankWeight(rankWeight);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setLoaderField(loaderField);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_CATALOG_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="CATALOG_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getCatalogId() {
        return this.catalogId;
    }

    public void setCatalogId(Long catalogId) {
        this.catalogId = catalogId;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC", nullable=false, length=50)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="SHIPPING_MESSAGE", length=1024)
    public String getShippingMessage() {
        return this.shippingMessage;
    }

    public void setShippingMessage(String shippingMessage) {
        this.shippingMessage = shippingMessage;
        setDirty(true);
    }

    
    @Column(name="CATALOG_STATUS_CD", nullable=false, length=30)
    public String getCatalogStatusCd() {
        return this.catalogStatusCd;
    }

    public void setCatalogStatusCd(String catalogStatusCd) {
        this.catalogStatusCd = catalogStatusCd;
        setDirty(true);
    }

    
    @Column(name="CATALOG_TYPE_CD", nullable=false, length=30)
    public String getCatalogTypeCd() {
        return this.catalogTypeCd;
    }

    public void setCatalogTypeCd(String catalogTypeCd) {
        this.catalogTypeCd = catalogTypeCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFF_DATE", length=7)
    public Date getEffDate() {
        return this.effDate;
    }

    public void setEffDate(Date effDate) {
        this.effDate = effDate;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXP_DATE", length=7)
    public Date getExpDate() {
        return this.expDate;
    }

    public void setExpDate(Date expDate) {
        this.expDate = expDate;
        setDirty(true);
    }

    
    @Column(name="RANK_WEIGHT", columnDefinition="number", precision=38, scale=0)
    public Long getRankWeight() {
        return this.rankWeight;
    }

    public void setRankWeight(Long rankWeight) {
        this.rankWeight = rankWeight;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="LOADER_FIELD", length=50)
    public String getLoaderField() {
        return this.loaderField;
    }

    public void setLoaderField(String loaderField) {
        this.loaderField = loaderField;
        setDirty(true);
    }




}


