package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * CostCenterData generated by hbm2java
*/
@Entity
@Table(name="CLW_COST_CENTER")
public class CostCenterData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String COST_CENTER_ID = "costCenterId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String COST_CENTER_STATUS_CD = "costCenterStatusCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String COST_CENTER_TYPE_CD = "costCenterTypeCd";
    public static final String ALLOCATE_FREIGHT = "allocateFreight";
    public static final String ALLOCATE_DISCOUNT = "allocateDiscount";
    public static final String COST_CENTER_TAX_TYPE = "costCenterTaxType";
    public static final String STORE_ID = "storeId";
    public static final String COST_CENTER_CODE = "costCenterCode";
    public static final String NO_BUDGET = "noBudget";

    private Long costCenterId;
    private String shortDesc;
    private String costCenterStatusCd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private String costCenterTypeCd;
    private String allocateFreight;
    private String allocateDiscount;
    private String costCenterTaxType;
    private Long storeId;
    private String costCenterCode;
    private String noBudget;

    public CostCenterData() {
    }
	
    public CostCenterData(String shortDesc, String costCenterStatusCd, Date addDate, Date modDate) {
        this.setShortDesc(shortDesc);
        this.setCostCenterStatusCd(costCenterStatusCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public CostCenterData(String shortDesc, String costCenterStatusCd, Date addDate, String addBy, Date modDate, String modBy, String costCenterTypeCd, String allocateFreight, String allocateDiscount, String costCenterTaxType, Long storeId, String costCenterCode, String noBudget) {
        this.setShortDesc(shortDesc);
        this.setCostCenterStatusCd(costCenterStatusCd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setCostCenterTypeCd(costCenterTypeCd);
        this.setAllocateFreight(allocateFreight);
        this.setAllocateDiscount(allocateDiscount);
        this.setCostCenterTaxType(costCenterTaxType);
        this.setStoreId(storeId);
        this.setCostCenterCode(costCenterCode);
        this.setNoBudget(noBudget);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_COST_CENTER_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="COST_CENTER_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getCostCenterId() {
        return this.costCenterId;
    }

    public void setCostCenterId(Long costCenterId) {
        this.costCenterId = costCenterId;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC", nullable=false, length=30)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="COST_CENTER_STATUS_CD", nullable=false, length=30)
    public String getCostCenterStatusCd() {
        return this.costCenterStatusCd;
    }

    public void setCostCenterStatusCd(String costCenterStatusCd) {
        this.costCenterStatusCd = costCenterStatusCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="COST_CENTER_TYPE_CD")
    public String getCostCenterTypeCd() {
        return this.costCenterTypeCd;
    }

    public void setCostCenterTypeCd(String costCenterTypeCd) {
        this.costCenterTypeCd = costCenterTypeCd;
        setDirty(true);
    }

    
    @Column(name="ALLOCATE_FREIGHT", length=30)
    public String getAllocateFreight() {
        return this.allocateFreight;
    }

    public void setAllocateFreight(String allocateFreight) {
        this.allocateFreight = allocateFreight;
        setDirty(true);
    }

    
    @Column(name="ALLOCATE_DISCOUNT", length=30)
    public String getAllocateDiscount() {
        return this.allocateDiscount;
    }

    public void setAllocateDiscount(String allocateDiscount) {
        this.allocateDiscount = allocateDiscount;
        setDirty(true);
    }

    
    @Column(name="COST_CENTER_TAX_TYPE", length=30)
    public String getCostCenterTaxType() {
        return this.costCenterTaxType;
    }

    public void setCostCenterTaxType(String costCenterTaxType) {
        this.costCenterTaxType = costCenterTaxType;
        setDirty(true);
    }

    
    @Column(name="STORE_ID", columnDefinition="number", precision=38, scale=0)
    public Long getStoreId() {
        return this.storeId;
    }

    public void setStoreId(Long storeId) {
        this.storeId = storeId;
        setDirty(true);
    }

    
    @Column(name="COST_CENTER_CODE", length=30)
    public String getCostCenterCode() {
        return this.costCenterCode;
    }

    public void setCostCenterCode(String costCenterCode) {
        this.costCenterCode = costCenterCode;
        setDirty(true);
    }

    
    @Column(name="NO_BUDGET", length=30)
    public String getNoBudget() {
        return this.noBudget;
    }

    public void setNoBudget(String noBudget) {
        this.noBudget = noBudget;
        setDirty(true);
    }




}


