package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * CountryPropertyData generated by hbm2java
*/
@Entity
@Table(name="CLW_COUNTRY_PROPERTY")
public class CountryPropertyData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String COUNTRY_PROPERTY_ID = "countryPropertyId";
    public static final String COUNTRY_ID = "countryId";
    public static final String COUNTRY_PROPERTY_CD = "countryPropertyCd";
    public static final String VALUE = "value";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    private Long countryPropertyId;
    private Long countryId;
    private String countryPropertyCd;
    private String value;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;

    public CountryPropertyData() {
    }
	
    public CountryPropertyData(Long countryId, String countryPropertyCd, Date addDate, Date modDate) {
        this.setCountryId(countryId);
        this.setCountryPropertyCd(countryPropertyCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public CountryPropertyData(Long countryId, String countryPropertyCd, String value, Date addDate, String addBy, Date modDate, String modBy) {
        this.setCountryId(countryId);
        this.setCountryPropertyCd(countryPropertyCd);
        this.setValue(value);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_COUNTRY_PROPERTY_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="COUNTRY_PROPERTY_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getCountryPropertyId() {
        return this.countryPropertyId;
    }

    public void setCountryPropertyId(Long countryPropertyId) {
        this.countryPropertyId = countryPropertyId;
        setDirty(true);
    }

    
    @Column(name="COUNTRY_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getCountryId() {
        return this.countryId;
    }

    public void setCountryId(Long countryId) {
        this.countryId = countryId;
        setDirty(true);
    }

    
    @Column(name="COUNTRY_PROPERTY_CD", nullable=false, length=30)
    public String getCountryPropertyCd() {
        return this.countryPropertyCd;
    }

    public void setCountryPropertyCd(String countryPropertyCd) {
        this.countryPropertyCd = countryPropertyCd;
        setDirty(true);
    }

    
    @Column(name="CLW_VALUE", length=12)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }




}


