package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;
/**
 * EmailData generated by hbm2java
*/
@Entity
@Table(name="CLW_EMAIL")
public class EmailData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String EMAIL_ID = "emailId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String USER_ID = "userId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String EMAIL_TYPE_CD = "emailTypeCd";
    public static final String EMAIL_STATUS_CD = "emailStatusCd";
    public static final String EMAIL_ADDRESS = "emailAddress";
    public static final String PRIMARY_IND = "primaryInd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String CONTACT_ID = "contactId";

    private Long emailId;
    private Long busEntityId;
    private Long userId;
    private String shortDesc;
    private String emailTypeCd;
    private String emailStatusCd;
    private String emailAddress;
    private Boolean primaryInd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private Long contactId;

    public EmailData() {
    }
	
    public EmailData(String emailTypeCd, String emailStatusCd, Date addDate, Date modDate) {
        this.setEmailTypeCd(emailTypeCd);
        this.setEmailStatusCd(emailStatusCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public EmailData(Long busEntityId, Long userId, String shortDesc, String emailTypeCd, String emailStatusCd, String emailAddress, Boolean primaryInd, Date addDate, String addBy, Date modDate, String modBy, Long contactId) {
        this.setBusEntityId(busEntityId);
        this.setUserId(userId);
        this.setShortDesc(shortDesc);
        this.setEmailTypeCd(emailTypeCd);
        this.setEmailStatusCd(emailStatusCd);
        this.setEmailAddress(emailAddress);
        this.setPrimaryInd(primaryInd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setContactId(contactId);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_EMAIL_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="EMAIL_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getEmailId() {
        return this.emailId;
    }

    public void setEmailId(Long emailId) {
        this.emailId = emailId;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_ID", columnDefinition="number", precision=38, scale=0)
    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    
    @Column(name="USER_ID", columnDefinition="number", precision=38, scale=0)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC", length=81)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="EMAIL_TYPE_CD", nullable=false, length=30)
    public String getEmailTypeCd() {
        return this.emailTypeCd;
    }

    public void setEmailTypeCd(String emailTypeCd) {
        this.emailTypeCd = emailTypeCd;
        setDirty(true);
    }

    
    @Column(name="EMAIL_STATUS_CD", nullable=false, length=30)
    public String getEmailStatusCd() {
        return this.emailStatusCd;
    }

    public void setEmailStatusCd(String emailStatusCd) {
        this.emailStatusCd = emailStatusCd;
        setDirty(true);
    }

    
    @Column(name="EMAIL_ADDRESS")
    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
        setDirty(true);
    }

    @Type(type="com.espendwise.manta.support.hibernate.NumberBooleanType")
    @Column(name="PRIMARY_IND", columnDefinition="number", precision=1, scale=0)
    public Boolean getPrimaryInd() {
        return this.primaryInd;
    }

    public void setPrimaryInd(Boolean primaryInd) {
        this.primaryInd = primaryInd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="CONTACT_ID", columnDefinition="number", precision=38, scale=0)
    public Long getContactId() {
        return this.contactId;
    }

    public void setContactId(Long contactId) {
        this.contactId = contactId;
        setDirty(true);
    }




}


