package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * FiscalCalenderData generated by hbm2java
*/
@Entity
@Table(name="CLW_FISCAL_CALENDER")
public class FiscalCalenderData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String FISCAL_CALENDER_ID = "fiscalCalenderId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String PERIOD_CD = "periodCd";
    public static final String MMDD1 = "mmdd1";
    public static final String MMDD2 = "mmdd2";
    public static final String MMDD3 = "mmdd3";
    public static final String MMDD4 = "mmdd4";
    public static final String MMDD5 = "mmdd5";
    public static final String MMDD6 = "mmdd6";
    public static final String MMDD7 = "mmdd7";
    public static final String MMDD8 = "mmdd8";
    public static final String MMDD9 = "mmdd9";
    public static final String MMDD10 = "mmdd10";
    public static final String MMDD11 = "mmdd11";
    public static final String MMDD12 = "mmdd12";
    public static final String MMDD13 = "mmdd13";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String FISCAL_YEAR = "fiscalYear";

    private Long fiscalCalenderId;
    private Long busEntityId;
    private String shortDesc;
    private String periodCd;
    private String mmdd1;
    private String mmdd2;
    private String mmdd3;
    private String mmdd4;
    private String mmdd5;
    private String mmdd6;
    private String mmdd7;
    private String mmdd8;
    private String mmdd9;
    private String mmdd10;
    private String mmdd11;
    private String mmdd12;
    private String mmdd13;
    private Date effDate;
    private Date expDate;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private Integer fiscalYear;

    public FiscalCalenderData() {
    }
	
    public FiscalCalenderData(Long busEntityId, String shortDesc, String periodCd, Date effDate, Date addDate, Date modDate) {
        this.setBusEntityId(busEntityId);
        this.setShortDesc(shortDesc);
        this.setPeriodCd(periodCd);
        this.setEffDate(effDate);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public FiscalCalenderData(Long busEntityId, String shortDesc, String periodCd, String mmdd1, String mmdd2, String mmdd3, String mmdd4, String mmdd5, String mmdd6, String mmdd7, String mmdd8, String mmdd9, String mmdd10, String mmdd11, String mmdd12, String mmdd13, Date effDate, Date expDate, Date addDate, String addBy, Date modDate, String modBy, Integer fiscalYear) {
        this.setBusEntityId(busEntityId);
        this.setShortDesc(shortDesc);
        this.setPeriodCd(periodCd);
        this.setMmdd1(mmdd1);
        this.setMmdd2(mmdd2);
        this.setMmdd3(mmdd3);
        this.setMmdd4(mmdd4);
        this.setMmdd5(mmdd5);
        this.setMmdd6(mmdd6);
        this.setMmdd7(mmdd7);
        this.setMmdd8(mmdd8);
        this.setMmdd9(mmdd9);
        this.setMmdd10(mmdd10);
        this.setMmdd11(mmdd11);
        this.setMmdd12(mmdd12);
        this.setMmdd13(mmdd13);
        this.setEffDate(effDate);
        this.setExpDate(expDate);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setFiscalYear(fiscalYear);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_FISCAL_CALENDER_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="FISCAL_CALENDER_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getFiscalCalenderId() {
        return this.fiscalCalenderId;
    }

    public void setFiscalCalenderId(Long fiscalCalenderId) {
        this.fiscalCalenderId = fiscalCalenderId;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC", nullable=false, length=30)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="PERIOD_CD", nullable=false, length=30)
    public String getPeriodCd() {
        return this.periodCd;
    }

    public void setPeriodCd(String periodCd) {
        this.periodCd = periodCd;
        setDirty(true);
    }

    
    @Column(name="MMDD1", length=5)
    public String getMmdd1() {
        return this.mmdd1;
    }

    public void setMmdd1(String mmdd1) {
        this.mmdd1 = mmdd1;
        setDirty(true);
    }

    
    @Column(name="MMDD2", length=5)
    public String getMmdd2() {
        return this.mmdd2;
    }

    public void setMmdd2(String mmdd2) {
        this.mmdd2 = mmdd2;
        setDirty(true);
    }

    
    @Column(name="MMDD3", length=5)
    public String getMmdd3() {
        return this.mmdd3;
    }

    public void setMmdd3(String mmdd3) {
        this.mmdd3 = mmdd3;
        setDirty(true);
    }

    
    @Column(name="MMDD4", length=5)
    public String getMmdd4() {
        return this.mmdd4;
    }

    public void setMmdd4(String mmdd4) {
        this.mmdd4 = mmdd4;
        setDirty(true);
    }

    
    @Column(name="MMDD5", length=5)
    public String getMmdd5() {
        return this.mmdd5;
    }

    public void setMmdd5(String mmdd5) {
        this.mmdd5 = mmdd5;
        setDirty(true);
    }

    
    @Column(name="MMDD6", length=5)
    public String getMmdd6() {
        return this.mmdd6;
    }

    public void setMmdd6(String mmdd6) {
        this.mmdd6 = mmdd6;
        setDirty(true);
    }

    
    @Column(name="MMDD7", length=5)
    public String getMmdd7() {
        return this.mmdd7;
    }

    public void setMmdd7(String mmdd7) {
        this.mmdd7 = mmdd7;
        setDirty(true);
    }

    
    @Column(name="MMDD8", length=5)
    public String getMmdd8() {
        return this.mmdd8;
    }

    public void setMmdd8(String mmdd8) {
        this.mmdd8 = mmdd8;
        setDirty(true);
    }

    
    @Column(name="MMDD9", length=5)
    public String getMmdd9() {
        return this.mmdd9;
    }

    public void setMmdd9(String mmdd9) {
        this.mmdd9 = mmdd9;
        setDirty(true);
    }

    
    @Column(name="MMDD10", length=5)
    public String getMmdd10() {
        return this.mmdd10;
    }

    public void setMmdd10(String mmdd10) {
        this.mmdd10 = mmdd10;
        setDirty(true);
    }

    
    @Column(name="MMDD11", length=5)
    public String getMmdd11() {
        return this.mmdd11;
    }

    public void setMmdd11(String mmdd11) {
        this.mmdd11 = mmdd11;
        setDirty(true);
    }

    
    @Column(name="MMDD12", length=5)
    public String getMmdd12() {
        return this.mmdd12;
    }

    public void setMmdd12(String mmdd12) {
        this.mmdd12 = mmdd12;
        setDirty(true);
    }

    
    @Column(name="MMDD13", length=5)
    public String getMmdd13() {
        return this.mmdd13;
    }

    public void setMmdd13(String mmdd13) {
        this.mmdd13 = mmdd13;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFF_DATE", nullable=false, length=7)
    public Date getEffDate() {
        return this.effDate;
    }

    public void setEffDate(Date effDate) {
        this.effDate = effDate;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXP_DATE", length=7)
    public Date getExpDate() {
        return this.expDate;
    }

    public void setExpDate(Date expDate) {
        this.expDate = expDate;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="FISCAL_YEAR", columnDefinition="number", precision=5, scale=0)
    public Integer getFiscalYear() {
        return this.fiscalYear;
    }

    public void setFiscalYear(Integer fiscalYear) {
        this.fiscalYear = fiscalYear;
        setDirty(true);
    }




}


