package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * FiscalCalenderDetailData generated by hbm2java
*/
@Entity
@Table(name="CLW_FISCAL_CALENDER_DETAIL")
public class FiscalCalenderDetailData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String FISCAL_CALENDER_DETAIL_ID = "fiscalCalenderDetailId";
    public static final String FISCAL_CALENDER_ID = "fiscalCalenderId";
    public static final String PERIOD = "period";
    public static final String MMDD = "mmdd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    private Long fiscalCalenderDetailId;
    private Long fiscalCalenderId;
    private int period;
    private String mmdd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;

    public FiscalCalenderDetailData() {
    }
	
    public FiscalCalenderDetailData(Long fiscalCalenderId, int period, Date addDate, Date modDate) {
        this.setFiscalCalenderId(fiscalCalenderId);
        this.setPeriod(period);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public FiscalCalenderDetailData(Long fiscalCalenderId, int period, String mmdd, Date addDate, String addBy, Date modDate, String modBy) {
        this.setFiscalCalenderId(fiscalCalenderId);
        this.setPeriod(period);
        this.setMmdd(mmdd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_FISCAL_CALENDER_DETAIL_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="FISCAL_CALENDER_DETAIL_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getFiscalCalenderDetailId() {
        return this.fiscalCalenderDetailId;
    }

    public void setFiscalCalenderDetailId(Long fiscalCalenderDetailId) {
        this.fiscalCalenderDetailId = fiscalCalenderDetailId;
        setDirty(true);
    }

    
    @Column(name="FISCAL_CALENDER_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getFiscalCalenderId() {
        return this.fiscalCalenderId;
    }

    public void setFiscalCalenderId(Long fiscalCalenderId) {
        this.fiscalCalenderId = fiscalCalenderId;
        setDirty(true);
    }

    
    @Column(name="PERIOD", nullable=false, columnDefinition="number", precision=10, scale=0)
    public int getPeriod() {
        return this.period;
    }

    public void setPeriod(int period) {
        this.period = period;
        setDirty(true);
    }

    
    @Column(name="MMDD", length=5)
    public String getMmdd() {
        return this.mmdd;
    }

    public void setMmdd(String mmdd) {
        this.mmdd = mmdd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }




}


