package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * GroupData generated by hbm2java
*/
@Entity
@Table(name="CLW_GROUP")
public class GroupData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String GROUP_ID = "groupId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String GROUP_STATUS_CD = "groupStatusCd";
    public static final String GROUP_TYPE_CD = "groupTypeCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    private Long groupId;
    private String shortDesc;
    private String groupStatusCd;
    private String groupTypeCd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;

    public GroupData() {
    }
	
    public GroupData(String shortDesc, String groupStatusCd, String groupTypeCd, Date addDate, Date modDate) {
        this.setShortDesc(shortDesc);
        this.setGroupStatusCd(groupStatusCd);
        this.setGroupTypeCd(groupTypeCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public GroupData(String shortDesc, String groupStatusCd, String groupTypeCd, Date addDate, String addBy, Date modDate, String modBy) {
        this.setShortDesc(shortDesc);
        this.setGroupStatusCd(groupStatusCd);
        this.setGroupTypeCd(groupTypeCd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_GROUP_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="GROUP_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getGroupId() {
        return this.groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC", nullable=false, length=30)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="GROUP_STATUS_CD", nullable=false, length=30)
    public String getGroupStatusCd() {
        return this.groupStatusCd;
    }

    public void setGroupStatusCd(String groupStatusCd) {
        this.groupStatusCd = groupStatusCd;
        setDirty(true);
    }

    
    @Column(name="GROUP_TYPE_CD", nullable=false, length=30)
    public String getGroupTypeCd() {
        return this.groupTypeCd;
    }

    public void setGroupTypeCd(String groupTypeCd) {
        this.groupTypeCd = groupTypeCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }




}


