package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * LanguageData generated by hbm2java
*/
@Entity
@Table(name="CLW_LANGUAGE")
public class LanguageData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String LANGUAGE_ID = "languageId";
    public static final String SHORT_DESC = "shortDesc";
    public static final String UI_NAME = "uiName";
    public static final String LANGUAGE_CODE = "languageCode";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    private Long languageId;
    private String shortDesc;
    private String uiName;
    private String languageCode;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;

    public LanguageData() {
    }
	
    public LanguageData(String shortDesc, String uiName, String languageCode, Date addDate, Date modDate) {
        this.setShortDesc(shortDesc);
        this.setUiName(uiName);
        this.setLanguageCode(languageCode);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public LanguageData(String shortDesc, String uiName, String languageCode, Date addDate, String addBy, Date modDate, String modBy) {
        this.setShortDesc(shortDesc);
        this.setUiName(uiName);
        this.setLanguageCode(languageCode);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_LANGUAGE_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="LANGUAGE_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getLanguageId() {
        return this.languageId;
    }

    public void setLanguageId(Long languageId) {
        this.languageId = languageId;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC", nullable=false, length=64)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="UI_NAME", nullable=false, length=128)
    public String getUiName() {
        return this.uiName;
    }

    public void setUiName(String uiName) {
        this.uiName = uiName;
        setDirty(true);
    }

    
    @Column(name="LANGUAGE_CODE", nullable=false, length=2)
    public String getLanguageCode() {
        return this.languageCode;
    }

    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY", length=30)
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY", length=30)
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }




}


