package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * OrderAssocData generated by hbm2java
*/
@Entity
@Table(name="CLW_ORDER_ASSOC")
public class OrderAssocData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String ORDER_ASSOC_ID = "orderAssocId";
    public static final String ORDER1_ID = "order1Id";
    public static final String ORDER2_ID = "order2Id";
    public static final String ORDER_ASSOC_CD = "orderAssocCd";
    public static final String ORDER_ASSOC_STATUS_CD = "orderAssocStatusCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String WORK_ORDER_ITEM_ID = "workOrderItemId";
    public static final String SERVICE_TICKET_ID = "serviceTicketId";

    private Long orderAssocId;
    private Long order1Id;
    private Long order2Id;
    private String orderAssocCd;
    private String orderAssocStatusCd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private Long workOrderItemId;
    private Long serviceTicketId;

    public OrderAssocData() {
    }
	
    public OrderAssocData(Long order2Id, Date addDate, Date modDate) {
        this.setOrder2Id(order2Id);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public OrderAssocData(Long order1Id, Long order2Id, String orderAssocCd, String orderAssocStatusCd, Date addDate, String addBy, Date modDate, String modBy, Long workOrderItemId, Long serviceTicketId) {
        this.setOrder1Id(order1Id);
        this.setOrder2Id(order2Id);
        this.setOrderAssocCd(orderAssocCd);
        this.setOrderAssocStatusCd(orderAssocStatusCd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setWorkOrderItemId(workOrderItemId);
        this.setServiceTicketId(serviceTicketId);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_ORDER_ASSOC_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="ORDER_ASSOC_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getOrderAssocId() {
        return this.orderAssocId;
    }

    public void setOrderAssocId(Long orderAssocId) {
        this.orderAssocId = orderAssocId;
        setDirty(true);
    }

    
    @Column(name="ORDER1_ID", columnDefinition="number", precision=38, scale=0)
    public Long getOrder1Id() {
        return this.order1Id;
    }

    public void setOrder1Id(Long order1Id) {
        this.order1Id = order1Id;
        setDirty(true);
    }

    
    @Column(name="ORDER2_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getOrder2Id() {
        return this.order2Id;
    }

    public void setOrder2Id(Long order2Id) {
        this.order2Id = order2Id;
        setDirty(true);
    }

    
    @Column(name="ORDER_ASSOC_CD", length=30)
    public String getOrderAssocCd() {
        return this.orderAssocCd;
    }

    public void setOrderAssocCd(String orderAssocCd) {
        this.orderAssocCd = orderAssocCd;
        setDirty(true);
    }

    
    @Column(name="ORDER_ASSOC_STATUS_CD", length=30)
    public String getOrderAssocStatusCd() {
        return this.orderAssocStatusCd;
    }

    public void setOrderAssocStatusCd(String orderAssocStatusCd) {
        this.orderAssocStatusCd = orderAssocStatusCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="WORK_ORDER_ITEM_ID", columnDefinition="number", precision=38, scale=0)
    public Long getWorkOrderItemId() {
        return this.workOrderItemId;
    }

    public void setWorkOrderItemId(Long workOrderItemId) {
        this.workOrderItemId = workOrderItemId;
        setDirty(true);
    }

    
    @Column(name="SERVICE_TICKET_ID", columnDefinition="number", precision=38, scale=0)
    public Long getServiceTicketId() {
        return this.serviceTicketId;
    }

    public void setServiceTicketId(Long serviceTicketId) {
        this.serviceTicketId = serviceTicketId;
        setDirty(true);
    }




}


