package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Type;
/**
 * PhoneData generated by hbm2java
*/
@Entity
@Table(name="CLW_PHONE")
public class PhoneData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String PHONE_ID = "phoneId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String USER_ID = "userId";
    public static final String PHONE_COUNTRY_CD = "phoneCountryCd";
    public static final String PHONE_AREA_CODE = "phoneAreaCode";
    public static final String PHONE_NUM = "phoneNum";
    public static final String SHORT_DESC = "shortDesc";
    public static final String PHONE_TYPE_CD = "phoneTypeCd";
    public static final String PHONE_STATUS_CD = "phoneStatusCd";
    public static final String PRIMARY_IND = "primaryInd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String CONTACT_ID = "contactId";

    private Long phoneId;
    private Long busEntityId;
    private Long userId;
    private String phoneCountryCd;
    private String phoneAreaCode;
    private String phoneNum;
    private String shortDesc;
    private String phoneTypeCd;
    private String phoneStatusCd;
    private Boolean primaryInd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private Long contactId;

    public PhoneData() {
    }
	
    public PhoneData(String phoneTypeCd, String phoneStatusCd, Date addDate, Date modDate) {
        this.setPhoneTypeCd(phoneTypeCd);
        this.setPhoneStatusCd(phoneStatusCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public PhoneData(Long busEntityId, Long userId, String phoneCountryCd, String phoneAreaCode, String phoneNum, String shortDesc, String phoneTypeCd, String phoneStatusCd, Boolean primaryInd, Date addDate, String addBy, Date modDate, String modBy, Long contactId) {
        this.setBusEntityId(busEntityId);
        this.setUserId(userId);
        this.setPhoneCountryCd(phoneCountryCd);
        this.setPhoneAreaCode(phoneAreaCode);
        this.setPhoneNum(phoneNum);
        this.setShortDesc(shortDesc);
        this.setPhoneTypeCd(phoneTypeCd);
        this.setPhoneStatusCd(phoneStatusCd);
        this.setPrimaryInd(primaryInd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setContactId(contactId);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_PHONE_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="PHONE_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getPhoneId() {
        return this.phoneId;
    }

    public void setPhoneId(Long phoneId) {
        this.phoneId = phoneId;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_ID", columnDefinition="number", precision=38, scale=0)
    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    
    @Column(name="USER_ID", columnDefinition="number", precision=38, scale=0)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
        setDirty(true);
    }

    
    @Column(name="PHONE_COUNTRY_CD", length=30)
    public String getPhoneCountryCd() {
        return this.phoneCountryCd;
    }

    public void setPhoneCountryCd(String phoneCountryCd) {
        this.phoneCountryCd = phoneCountryCd;
        setDirty(true);
    }

    
    @Column(name="PHONE_AREA_CODE", length=3)
    public String getPhoneAreaCode() {
        return this.phoneAreaCode;
    }

    public void setPhoneAreaCode(String phoneAreaCode) {
        this.phoneAreaCode = phoneAreaCode;
        setDirty(true);
    }

    
    @Column(name="PHONE_NUM", length=60)
    public String getPhoneNum() {
        return this.phoneNum;
    }

    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC", length=30)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="PHONE_TYPE_CD", nullable=false, length=30)
    public String getPhoneTypeCd() {
        return this.phoneTypeCd;
    }

    public void setPhoneTypeCd(String phoneTypeCd) {
        this.phoneTypeCd = phoneTypeCd;
        setDirty(true);
    }

    
    @Column(name="PHONE_STATUS_CD", nullable=false, length=30)
    public String getPhoneStatusCd() {
        return this.phoneStatusCd;
    }

    public void setPhoneStatusCd(String phoneStatusCd) {
        this.phoneStatusCd = phoneStatusCd;
        setDirty(true);
    }

    @Type(type="com.espendwise.manta.support.hibernate.NumberBooleanType")
    @Column(name="PRIMARY_IND", columnDefinition="number", precision=1, scale=0)
    public Boolean getPrimaryInd() {
        return this.primaryInd;
    }

    public void setPrimaryInd(Boolean primaryInd) {
        this.primaryInd = primaryInd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="CONTACT_ID", columnDefinition="number", precision=38, scale=0)
    public Long getContactId() {
        return this.contactId;
    }

    public void setContactId(Long contactId) {
        this.contactId = contactId;
        setDirty(true);
    }




}


