package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * SiteWorkflowData generated by hbm2java
*/
@Entity
@Table(name="CLW_SITE_WORKFLOW")
public class SiteWorkflowData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String SITE_WORKFLOW_ID = "siteWorkflowId";
    public static final String WORKFLOW_ID = "workflowId";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String SITE_ID = "siteId";

    private Long siteWorkflowId;
    private Long workflowId;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private Long siteId;

    public SiteWorkflowData() {
    }
	
    public SiteWorkflowData(Date addDate, Date modDate) {
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public SiteWorkflowData(Long workflowId, Date addDate, String addBy, Date modDate, String modBy, Long siteId) {
        this.setWorkflowId(workflowId);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setSiteId(siteId);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_SITE_WORKFLOW_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="SITE_WORKFLOW_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getSiteWorkflowId() {
        return this.siteWorkflowId;
    }

    public void setSiteWorkflowId(Long siteWorkflowId) {
        this.siteWorkflowId = siteWorkflowId;
        setDirty(true);
    }

    
    @Column(name="WORKFLOW_ID", columnDefinition="number", precision=38, scale=0)
    public Long getWorkflowId() {
        return this.workflowId;
    }

    public void setWorkflowId(Long workflowId) {
        this.workflowId = workflowId;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    
    @Column(name="SITE_ID", columnDefinition="number", precision=38, scale=0)
    public Long getSiteId() {
        return this.siteId;
    }

    public void setSiteId(Long siteId) {
        this.siteId = siteId;
        setDirty(true);
    }




}


