package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * TemplateData generated by hbm2java
*/
@Entity
@Table(name="CLW_TEMPLATE")
public class TemplateData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String TEMPLATE_ID = "templateId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String NAME = "name";
    public static final String TYPE = "type";
    public static final String CONTENT = "content";
    public static final String ADD_BY = "addBy";
    public static final String ADD_DATE = "addDate";
    public static final String MOD_BY = "modBy";
    public static final String MOD_DATE = "modDate";

    private Long templateId;
    private Long busEntityId;
    private String name;
    private String type;
    private String content;
    private String addBy;
    private Date addDate;
    private String modBy;
    private Date modDate;

    public TemplateData() {
    }
	
    public TemplateData(String name, String type, String content, Date addDate, Date modDate) {
        this.setName(name);
        this.setType(type);
        this.setContent(content);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public TemplateData(Long busEntityId, String name, String type, String content, String addBy, Date addDate, String modBy, Date modDate) {
        this.setBusEntityId(busEntityId);
        this.setName(name);
        this.setType(type);
        this.setContent(content);
        this.setAddBy(addBy);
        this.setAddDate(addDate);
        this.setModBy(modBy);
        this.setModDate(modDate);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_TEMPLATE_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="TEMPLATE_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getTemplateId() {
        return this.templateId;
    }

    public void setTemplateId(Long templateId) {
        this.templateId = templateId;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_ID", columnDefinition="number", precision=38, scale=0)
    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    
    @Column(name="NAME", nullable=false, length=50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
        setDirty(true);
    }

    
    @Column(name="TYPE", nullable=false, length=30)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
        setDirty(true);
    }

    
    @Column(name="CONTENT", nullable=false, columnDefinition="clob")
    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }




}


