package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * UserAssocData generated by hbm2java
*/
@Entity
@Table(name="CLW_USER_ASSOC")
public class UserAssocData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String USER_ASSOC_ID = "userAssocId";
    public static final String USER_ID = "userId";
    public static final String BUS_ENTITY_ID = "busEntityId";
    public static final String USER_ASSOC_CD = "userAssocCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";
    public static final String LAST_USER_VISIT_DATE_TIME = "lastUserVisitDateTime";

    private Long userAssocId;
    private Long userId;
    private Long busEntityId;
    private String userAssocCd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;
    private Date lastUserVisitDateTime;

    public UserAssocData() {
    }
	
    public UserAssocData(String userAssocCd, Date addDate, Date modDate) {
        this.setUserAssocCd(userAssocCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public UserAssocData(Long userId, Long busEntityId, String userAssocCd, Date addDate, String addBy, Date modDate, String modBy, Date lastUserVisitDateTime) {
        this.setUserId(userId);
        this.setBusEntityId(busEntityId);
        this.setUserAssocCd(userAssocCd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
        this.setLastUserVisitDateTime(lastUserVisitDateTime);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_USER_ASSOC_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="USER_ASSOC_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getUserAssocId() {
        return this.userAssocId;
    }

    public void setUserAssocId(Long userAssocId) {
        this.userAssocId = userAssocId;
        setDirty(true);
    }

    
    @Column(name="USER_ID", columnDefinition="number", precision=38, scale=0)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
        setDirty(true);
    }

    
    @Column(name="BUS_ENTITY_ID", columnDefinition="number", precision=38, scale=0)
    public Long getBusEntityId() {
        return this.busEntityId;
    }

    public void setBusEntityId(Long busEntityId) {
        this.busEntityId = busEntityId;
        setDirty(true);
    }

    
    @Column(name="USER_ASSOC_CD", nullable=false, length=30)
    public String getUserAssocCd() {
        return this.userAssocCd;
    }

    public void setUserAssocCd(String userAssocCd) {
        this.userAssocCd = userAssocCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_USER_VISIT_DATE_TIME", length=7)
    public Date getLastUserVisitDateTime() {
        return this.lastUserVisitDateTime;
    }

    public void setLastUserVisitDateTime(Date lastUserVisitDateTime) {
        this.lastUserVisitDateTime = lastUserVisitDateTime;
        setDirty(true);
    }




}


