package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * UserData generated by hbm2java
*/
@Entity
@Table(name="CLW_USER")
public class UserData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String USER_ID = "userId";
    public static final String FIRST_NAME = "firstName";
    public static final String LAST_NAME = "lastName";
    public static final String USER_NAME = "userName";
    public static final String PASSWORD = "password";
    public static final String EFF_DATE = "effDate";
    public static final String EXP_DATE = "expDate";
    public static final String USER_STATUS_CD = "userStatusCd";
    public static final String USER_ROLE_CD = "userRoleCd";
    public static final String USER_TYPE_CD = "userTypeCd";
    public static final String REGISTER_DATE = "registerDate";
    public static final String LAST_ACTIVITY_DATE = "lastActivityDate";
    public static final String PREF_LOCALE_CD = "prefLocaleCd";
    public static final String WORKFLOW_ROLE_CD = "workflowRoleCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    private Long userId;
    private String firstName;
    private String lastName;
    private String userName;
    private String password;
    private Date effDate;
    private Date expDate;
    private String userStatusCd;
    private String userRoleCd;
    private String userTypeCd;
    private Date registerDate;
    private Date lastActivityDate;
    private String prefLocaleCd;
    private String workflowRoleCd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;

    public UserData() {
    }
	
    public UserData(String userStatusCd, String userRoleCd, String userTypeCd, String prefLocaleCd, String workflowRoleCd, Date addDate, Date modDate) {
        this.setUserStatusCd(userStatusCd);
        this.setUserRoleCd(userRoleCd);
        this.setUserTypeCd(userTypeCd);
        this.setPrefLocaleCd(prefLocaleCd);
        this.setWorkflowRoleCd(workflowRoleCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public UserData(String firstName, String lastName, String userName, String password, Date effDate, Date expDate, String userStatusCd, String userRoleCd, String userTypeCd, Date registerDate, Date lastActivityDate, String prefLocaleCd, String workflowRoleCd, Date addDate, String addBy, Date modDate, String modBy) {
        this.setFirstName(firstName);
        this.setLastName(lastName);
        this.setUserName(userName);
        this.setPassword(password);
        this.setEffDate(effDate);
        this.setExpDate(expDate);
        this.setUserStatusCd(userStatusCd);
        this.setUserRoleCd(userRoleCd);
        this.setUserTypeCd(userTypeCd);
        this.setRegisterDate(registerDate);
        this.setLastActivityDate(lastActivityDate);
        this.setPrefLocaleCd(prefLocaleCd);
        this.setWorkflowRoleCd(workflowRoleCd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
    }

    @SequenceGenerator(name="generator", sequenceName="CLW_USER_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="USER_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
        setDirty(true);
    }

    
    @Column(name="FIRST_NAME")
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
        setDirty(true);
    }

    
    @Column(name="LAST_NAME")
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
        setDirty(true);
    }

    
    @Column(name="USER_NAME")
    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
        setDirty(true);
    }

    
    @Column(name="PASSWORD", length=35)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFF_DATE", length=7)
    public Date getEffDate() {
        return this.effDate;
    }

    public void setEffDate(Date effDate) {
        this.effDate = effDate;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EXP_DATE", length=7)
    public Date getExpDate() {
        return this.expDate;
    }

    public void setExpDate(Date expDate) {
        this.expDate = expDate;
        setDirty(true);
    }

    
    @Column(name="USER_STATUS_CD", nullable=false, length=30)
    public String getUserStatusCd() {
        return this.userStatusCd;
    }

    public void setUserStatusCd(String userStatusCd) {
        this.userStatusCd = userStatusCd;
        setDirty(true);
    }

    
    @Column(name="USER_ROLE_CD", nullable=false)
    public String getUserRoleCd() {
        return this.userRoleCd;
    }

    public void setUserRoleCd(String userRoleCd) {
        this.userRoleCd = userRoleCd;
        setDirty(true);
    }

    
    @Column(name="USER_TYPE_CD", nullable=false, length=30)
    public String getUserTypeCd() {
        return this.userTypeCd;
    }

    public void setUserTypeCd(String userTypeCd) {
        this.userTypeCd = userTypeCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REGISTER_DATE", length=7)
    public Date getRegisterDate() {
        return this.registerDate;
    }

    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_ACTIVITY_DATE", length=7)
    public Date getLastActivityDate() {
        return this.lastActivityDate;
    }

    public void setLastActivityDate(Date lastActivityDate) {
        this.lastActivityDate = lastActivityDate;
        setDirty(true);
    }

    
    @Column(name="PREF_LOCALE_CD", nullable=false, length=30)
    public String getPrefLocaleCd() {
        return this.prefLocaleCd;
    }

    public void setPrefLocaleCd(String prefLocaleCd) {
        this.prefLocaleCd = prefLocaleCd;
        setDirty(true);
    }

    
    @Column(name="WORKFLOW_ROLE_CD", nullable=false, length=30)
    public String getWorkflowRoleCd() {
        return this.workflowRoleCd;
    }

    public void setWorkflowRoleCd(String workflowRoleCd) {
        this.workflowRoleCd = workflowRoleCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY")
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY")
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }




}


