package com.espendwise.manta.model.data;
// Generated by Hibernate Tools


import com.espendwise.manta.model.TableObject;
import com.espendwise.manta.model.ValueObject;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
/**
 * WoRefCdData generated by hbm2java
*/
@Entity
@Table(name="WO_REF_CD")
public class WoRefCdData extends ValueObject implements TableObject,java.io.Serializable {

    private static final long serialVersionUID = -1;

    public static final String REF_CD_ID = "refCdId";
    public static final String REF_CD = "refCd";
    public static final String SHORT_DESC = "shortDesc";
    public static final String VALUE = "value";
    public static final String REF_CD_TYPE = "refCdType";
    public static final String REF_STATUS_CD = "refStatusCd";
    public static final String ADD_DATE = "addDate";
    public static final String ADD_BY = "addBy";
    public static final String MOD_DATE = "modDate";
    public static final String MOD_BY = "modBy";

    private Long refCdId;
    private String refCd;
    private String shortDesc;
    private String value;
    private String refCdType;
    private String refStatusCd;
    private Date addDate;
    private String addBy;
    private Date modDate;
    private String modBy;

    public WoRefCdData() {
    }
	
    public WoRefCdData(String refCd, String shortDesc, String value, String refCdType, String refStatusCd, Date addDate, Date modDate) {
        this.setRefCd(refCd);
        this.setShortDesc(shortDesc);
        this.setValue(value);
        this.setRefCdType(refCdType);
        this.setRefStatusCd(refStatusCd);
        this.setAddDate(addDate);
        this.setModDate(modDate);
    }

    public WoRefCdData(String refCd, String shortDesc, String value, String refCdType, String refStatusCd, Date addDate, String addBy, Date modDate, String modBy) {
        this.setRefCd(refCd);
        this.setShortDesc(shortDesc);
        this.setValue(value);
        this.setRefCdType(refCdType);
        this.setRefStatusCd(refStatusCd);
        this.setAddDate(addDate);
        this.setAddBy(addBy);
        this.setModDate(modDate);
        this.setModBy(modBy);
    }

    @SequenceGenerator(name="generator", sequenceName="WO_REF_CD_SEQ")
    @Id 
    @GeneratedValue(strategy=javax.persistence.GenerationType.SEQUENCE, generator="generator")     
    @Column(name="REF_CD_ID", nullable=false, columnDefinition="number", precision=38, scale=0)
    public Long getRefCdId() {
        return this.refCdId;
    }

    public void setRefCdId(Long refCdId) {
        this.refCdId = refCdId;
        setDirty(true);
    }

    
    @Column(name="REF_CD", nullable=false, length=30)
    public String getRefCd() {
        return this.refCd;
    }

    public void setRefCd(String refCd) {
        this.refCd = refCd;
        setDirty(true);
    }

    
    @Column(name="SHORT_DESC", nullable=false)
    public String getShortDesc() {
        return this.shortDesc;
    }

    public void setShortDesc(String shortDesc) {
        this.shortDesc = shortDesc;
        setDirty(true);
    }

    
    @Column(name="WO_VALUE", nullable=false)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
        setDirty(true);
    }

    
    @Column(name="REF_CD_TYPE", nullable=false, length=30)
    public String getRefCdType() {
        return this.refCdType;
    }

    public void setRefCdType(String refCdType) {
        this.refCdType = refCdType;
        setDirty(true);
    }

    
    @Column(name="REF_STATUS_CD", nullable=false, length=30)
    public String getRefStatusCd() {
        return this.refStatusCd;
    }

    public void setRefStatusCd(String refStatusCd) {
        this.refStatusCd = refStatusCd;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_DATE", nullable=false, length=7)
    public Date getAddDate() {
        return this.addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
        setDirty(true);
    }

    
    @Column(name="ADD_BY", length=30)
    public String getAddBy() {
        return this.addBy;
    }

    public void setAddBy(String addBy) {
        this.addBy = addBy;
        setDirty(true);
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MOD_DATE", nullable=false, length=7)
    public Date getModDate() {
        return this.modDate;
    }

    public void setModDate(Date modDate) {
        this.modDate = modDate;
        setDirty(true);
    }

    
    @Column(name="MOD_BY", length=30)
    public String getModBy() {
        return this.modBy;
    }

    public void setModBy(String modBy) {
        this.modBy = modBy;
        setDirty(true);
    }




}


